### ISSUE TITLE
Switch all shading computations to single-precision (float)

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1049]

**Comment by Narann** [comment]
I can't agree more! :)

**Comment by dictoon** [comment]
We've long been planning this, and Esteban has already done some work in that direction.

To summarize:

  - Geometry storage (in memory): single-precision, but configurable at compile-time.

  - Geometry computations: double precision. That solves entire classes of issues, such as teapot-in-stadium situations.

  - Color pipeline: single precision.

  - Shading computations: double precision. This is what we plan to change: double precision buys us nothing here.

**Comment by Narann** [comment]
> Geometry computations: double precision. That solves entire classes of issues, such as teapot-in-stadium situations.

I would argue you can get such speed improvements with floats that it would worth the production tradeoff to consider own to split your assets. :)

But I understand most appleseed users want turnkey renderer. I just say double precision decrease performances a lot.

**Comment by dictoon** [comment]
Done.
