### ISSUE TITLE
Endless passes under Windows?

### ISSUE THREAD

**Issue by crydalch** [appleseedhq/appleseed#1085]
In playing around with AppleSeed Studio on a Windows laptop (I'm primary a Linux user, FWIW), I'm finding my Final Renders don't seem to finish. After a few passes, it just keeps rendering and rendering, with the log reporting 'beginning pass N'; I let it go up to nearly 400, but it never finished, even with a resolution of 240x240, and turning off unlimited bounces.

![20160910140634](https://cloud.githubusercontent.com/assets/458856/18412574/d3b4992e-775f-11e6-9a91-d87129d988de.png)

Has anyone else seen this before? I'm not doing anything special, and it doesn't seem to matter which scene (I've been messing with the material tester scenes). Or is there a setting I just haven't found somewhere? 

The build I downloaded is **_appleseed-1.4.0-beta-0-g42ba647-win64-vs120-sse42.zip_** under Windows 10.

Thanks!

**Comment by crydalch** [comment]
I just discovered that this problem does _not_ appear when doing a Final Render on the built-in Cornell Box scene... No idea what that means, but might be a clue?

**Comment by est77** [comment]
I cannot reproduce this problem on linux.

The number of render passes is set in the render settings, when selecting final in configuration menu.

![screenshot_2016-09-10_20-47-27](https://cloud.githubusercontent.com/assets/409013/18412784/e3ef428e-7797-11e6-910e-a1c40c587b23.png)

**Comment by dictoon** [comment]
@crydalch The number of passes for this scene (material_tester_red_plastic.appleseed) is 100000, so it's going to render essentially forever. As Esteban pointed out, you can adjust the number of passes in the render settings dialog.

We'll adjust this demo scene to use a more reasonable number of passes. Thanks for pointing this out.

**Comment by crydalch** [comment]
Gah, how did I miss that! Shall I change the title of the
issue/description, or just close it?

**Comment by dictoon** [comment]
You can close it, I've updated the few demo scenes that were using an unreasonable number of passes. The revised scenes will be made available together with the next release, due imminently (tomorrow?).

**Comment by crydalch** [comment]
Sounds good, thanks @dictoon!

Closing, already fixed/being fixed. Cheers!
