### ISSUE TITLE
as_maya_areaLight.oso contains garbage that results in syntax errors at loading

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1176]
On both Esteban's machine and mine, that file contains uninitialized matrix parameters.

Esteban's version of the file (compiled with oslc 1.7.4):

    oparam	matrix	out_matrix	0 0 -1.3590819e-11 4.5856091e-41 -9.7107791e-27 4.5913544e-41 -9.7113831e-27 4.5913544e-41 1.3118252e-37 0 -7.762992e-09 4.5856091e-41 1.4413581e-37 0 -7.4269604e-09 4.5856091e-41		%meta{string,maya_attribute_name,"matrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{2147483647,-1}
    oparam	matrix	out_inverseMatrix	0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0		%meta{string,maya_attribute_name,"inverseMatrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"Inverse Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{3,3} %initexpr
    oparam	matrix	out_worldMatrix	0 0 -1.2545481e-11 4.5856091e-41 -9.7107791e-27 4.5913544e-41 -9.7113831e-27 4.5913544e-41 1.3118252e-37 0 -7.762992e-09 4.5856091e-41 1.4419088e-37 0 -7.4269604e-09 4.5856091e-41		%meta{string,maya_attribute_name,"worldMatrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"World Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{2147483647,-1}

My version of the file (compiled with oslc 1.6.8):

    oparam	matrix	out_matrix	0 0 4.7087743e-38 4.5905136e-41 0 0 7.2719816e+27 3.7835059e-44 7.2719816e+27 3.7835059e-44 0 0 -nan -nan 7.2719816e+27 3.7835059e-44		%meta{string,maya_attribute_name,"matrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{2147483647,-1}
    oparam	matrix	out_inverseMatrix	0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0		%meta{string,maya_attribute_name,"inverseMatrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"Inverse Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{4,4} %initexpr
    oparam	matrix	out_worldMatrix	0 0 4.7087743e-38 4.5905136e-41 0 0 7.2719816e+27 3.7835059e-44 7.2719816e+27 3.7835059e-44 0 0 -nan -nan 7.2719816e+27 3.7835059e-44		%meta{string,maya_attribute_name,"worldMatrix"} %meta{string,maya_attribute_type,"matrix"} %meta{string,label,"World Matrix"} %meta{string,widget,"null"}  %read{2147483647,-1} %write{2147483647,-1}

Notice the NaN values.

In my case, the file completely refuses to load, presumably because of these NaN.

**Comment by luisbarrancos** [comment]
Screenshot attached, values for (object to camera), inverse object to camera, object to world, inverse object to world matrices

```
// Warning: osl: Shader warning [as_maya_areaLight]: mats = 3.436129e+00 -1.133390e+00 1.745268e+00 0.000000e+00 -2.080993e+00 -1.871450e+00 2.881780e+00 0.000000e+00 4.937707e-16 -3.369067e+00 -2.187898e+00 0.000000e+00 7.142889e+00 7.568765e+00 -2.948246e+01 1.000000e+00,
 = 2.129280e-01 -1.289538e-01 -1.256999e-09 0.000000e+00 -7.023326e-02 -1.159689e-01 -2.087724e-01 0.000000e+00 1.081497e-01 1.785764e-01 -1.355784e-01 0.000000e+00 2.199178e+00 7.063716e+00 -2.417035e+00 1.000000e+00,
 = 4.017152e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 -7.379389e-16 4.017152e+00 0.000000e+00 0.000000e+00 -4.017152e+00 -7.379389e-16 0.000000e+00 2.728972e+00 6.275922e+00 -9.283986e+00 1.000000e+00,
 = 2.489326e-01 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 -4.572817e-17 -2.489326e-01 0.000000e+00 0.000000e+00 2.489326e-01 -4.572817e-17 0.000000e+00 -6.793300e-01 2.311086e+00 1.562281e+00 1.000000e+00 // 
```

![arealight](https://cloud.githubusercontent.com/assets/387352/21469215/5709afaa-ca79-11e6-8498-3d79d4d55740.png)

**Comment by dictoon** [comment]
I confirm that the problem appears to be fixed on my end. Closing this issue. Thanks!
