### ISSUE TITLE
Disable "warnings as errors" in optimized (Ship?) builds

### ISSUE THREAD

**Issue by davidgiven** [appleseedhq/appleseed#1234]
I've just tried to build Appleseed from source on Linux, and it errors out due to warnings about `auto_ptr<>` being deprecated.

Using -Werror isn't a good idea in release code --- because compilers are free to add warnings at any time, it introduces a dependency on a specific compiler version. If a release is buildable with version X of the compiler, but then version X+1 adds a new warning, that will cause a build breakage on version X+1.

This was with the 1.6.0-beta release from github (so I don't know whether this is still an issue with 1.7.0-beta). I've got gcc 6.2.1.

Oh, and I flipped the obvious-looking switch in CMakeLists.txt and reran cmake, but the resulting makefiles still had -Werror set. My cmake-fu isn't good enough to figure out why --- it's entirely possible I was just doing this wrong.

**Comment by est77** [comment]
I think that what we want is to fix all warnings, instead of disabling -Werror.
Could you provide us with the exact warning and the steps to reproduce it?

Thanks!

**Comment by davidgiven** [comment]
The trouble is that you can only fix the warnings your compiler produces. You can't fix the warnings that other compilers produce, because you don't have those compilers, and you don't know what warnings they produce. Different compilers produce different warnings --- there's no standard.

So making them errors simply causes build failures on environments which don't match yours. Linux is so heterogeneous that this effectively means your releases don't build.

`-Werror` is the right thing to do when developing, because you want developers to fix the warnings. But it's the wrong thing to do for releases, because your target audience is end users, and they can't be expected to have to fix your code to make it work.

As I said above, the warning is that `autoptr<>` is deprecated, and it happens when building with gcc 6.2.1 (e.g. on a recent Debian).

**Comment by dictoon** [comment]
Hello David,

We discussed this topic and we think you're right. There's little value in breaking the build for non-developers. We'll disable warnings as errors in optimized builds.

We're also adding gcc 6 in C++03 mode to the build matrix of our CI server:
https://github.com/appleseedhq/appleseed/pull/1235/files

Thanks.

**Comment by dictoon** [comment]
Note that in the meantime, you can also pass

    -DWARNINGS_AS_ERRORS=OFF

on CMake's command line to allow compiling without editing any file.

**Comment by davidgiven** [comment]
That's awesome --- thanks!

I did try setting WARNINGS_AS_ERRORS to OFF in the CMakeLists.txt file, but it apparently had no effect. But setting the flag on the command line works fine. *shrug* No idea what's going on there.

**Comment by dictoon** [comment]
Weird, it should have worked... Here's the code: https://github.com/appleseedhq/appleseed/blob/master/src/cmake/config/linux-gcc.txt#L75-L80

Would *deeply* appreciated if you could figure out why it isn't working :)

**Comment by est77** [comment]
One thing that works for us in Travis when using gcc 6 is:
-DUSE_CPP11

**Comment by dictoon** [comment]
> I did try setting WARNINGS_AS_ERRORS to OFF in the CMakeLists.txt file, but it apparently had no effect.

Ah, indeed, modifying the `CMakeLists.txt` file (which you are not supposed to do in fact) will only change the default value for that particular option, _not_ the current value (which is in `CMakeCache.txt`). That's why it had no effect.

**Comment by luisbarrancos** [comment]
@dictoon warnings as errors will be off in *Release* and *Ship* builds

**Comment by luisbarrancos** [comment]
This should be fixed now. Setting to *Ship* or *Release* changes the status of *warnings as errors* to **OFF** and forces the cache refresh for the variable. Other build types, *Profile* and *Debug* default to **ON**.

**Comment by dictoon** [comment]
Done, thanks a lot @luisbarrancos!
