### ISSUE TITLE
Add optional final gathering step to SPPM

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1247]
Like in traditional photon mapping, the role of 1-bounce final gathering is to defer photon lookups to the second diffuse bounce, thus hiding most of the artifacts due to directly visualizing photon density estimations.

The default should probably be 1 bounce of final gathering.

**Comment by Aakash1312** [comment]
I have created a pull request for the issue #1325

**Comment by dictoon** [comment]
Yes.
