### ISSUE TITLE
F-number parameter of thin lens camera expressed in wrong space?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1270]

**Comment by dictoon** [comment]
Not a bug in the code. The scene where this problem was discovered (the shader ball v2 scene) had a film size of 1024 m x 1024 m (!) requiring F-numbers in the 100,000s to get reasonable results.

**Comment by Narann** [comment]
What about writing a warning for huge film size values?

**Comment by dictoon** [comment]
Not really since we don't know in what units it (and the rest of the scene) is expressed.

**Comment by Narann** [comment]
You're right, we can maybe rely on a ratio. If the film size/focal length is too high, print a warning.

**Comment by dictoon** [comment]
Since focal length is derived from film size, this wouldn't help either...

Maybe we could do a check based on the focus distance / focal length ratio but this seems a bit contrived...
