### ISSUE TITLE
Emit warning if BSSRDF used on mesh without vertex normals

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1275]

**Comment by dictoon** [comment]
Suggestion for the text of the warning:

    "instance \"%s\" has a subsurface scattering material but object \"%s\" does not have vertex normals."

**Comment by ucanbizon** [comment]
I would like to take this issue to fix.

**Comment by dictoon** [comment]
Actually, we're not sure we want to do this issue anymore. I'm going to close it for now.

May I suggest this issue instead? https://github.com/appleseedhq/appleseed/issues/1267

Or one of these: https://github.com/appleseedhq/appleseed/issues/1196 https://github.com/appleseedhq/appleseed/issues/988

**Comment by ucanbizon** [comment]
Of course.

**Comment by ucanbizon** [comment]
Sure.
