### ISSUE TITLE
Add separate specular bounce control to PT lighting engine

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1286]

**Comment by dictoon** [comment]
Related to, or duplicate of #914.

**Comment by jayantsaraf** [comment]
i will like to take this issue. can you pleas give a little description about this issue

**Comment by dictoon** [comment]
Right now we have a single bounce limit, regardless of the type of scattering (diffuse, glossy, specular, subsurface...) What we want is to introduce separate controls for each type of scattering, starting with one for the number of specular bounces.

This implies at least:
- Adding a settings to the Rendering Settings dialog
- Honoring that settings in the path tracer, light tracer and the SPPM lighting engine
- Making sure we keep compatibility with existing projects

If you have rendering experience, this should speak to you. If you are a complete beginner when it comes to ray tracing / path tracing, I'm afraid it's going to be a little bit too much to chew.

**Comment by Aakash1312** [comment]
Fixed in this pull request
https://github.com/appleseedhq/appleseed/pull/1368

**Comment by dictoon** [comment]
Done.
