### ISSUE TITLE
Remove redundant CMake options

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1292]
In practice, `WITH_TOOLS` and `WITH_CLI` are never set to off. Let's remove them.

There's also no point in `WITH_DISNEY_MATERIAL`, let's remove it as well.

Nobody is being  sued for using the Normalized Diffusion BSSRDF in an open source project, so let's remove `WITH_NORMALIZED_DIFFUSION_BSSRDF`.

The only Partio code we have is in a unit test; let's get rid of it and of `WITH_PARTIO`.

**Comment by est77** [comment]
And WITH_ALEMBIC, we can remove it too.

**Comment by luisbarrancos** [comment]
@dictoon do we require PartIO? It's a dependency on SeExpr and OSL, though optional (for the ptcread, write, etc)

**Comment by dictoon** [comment]
Nope, we can get rid of Partio.

**Comment by dictoon** [comment]
`WITH_NORMALIZED_DIFFUSION_BSSRDF` and `WITH_PARTIO` are gone. `WITH_DISNEY_MATERIAL` is will be gone imminently.

I think it makes sense to keep `WITH_TOOLS` and `WITH_CLI`.
