### ISSUE TITLE
Check implementation of GTR1MDF D and lambda functions

### ISSUE THREAD

**Issue by gospodnetic** [appleseedhq/appleseed#1308]
Currently GTR1MDF fails Weak White Furnace test with result 0.5
Check implementation of the formulas from  https://docs.chaosgroup.com/download/attachments/7147732/gtr_shadowing.pdf?version=2&modificationDate=1434539612000&api=v2

**Comment by est77** [comment]
Fixed in 71036823e764ace444345265afaa5da1d552b038
