### ISSUE TITLE
Invalid samples in sss_sets_comparison.appleseed test scene 

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#1324]
Does not seem related to SSS sets. Disabling them still generates invalid samples.

**Comment by dictoon** [comment]
Do you mean that rendering them lead to NaN/INF pixel samples?

**Comment by est77** [comment]
There's something in this scene that produces NaN / INF pixel samples, yes.
I played a bit with it and it seem the origin is subsurface scattering.
Disabling the SSS sets made no difference.

**Comment by Biart95** [comment]
The bug is located in the following fragment of code in separablebssrdf.cpp:
```c++
    // Compute the PDF of this incoming point.
    const float dot_nn = static_cast<float>(
        abs(dot(projection_basis.get_normal(), incoming_point.get_shading_normal())));
    incoming_point_prob = projection_axis_prob * disk_point_prob * dot_nn;

    // Weight the sample contribution with multiple importance sampling.
    const float mis_weight =
        compute_mis_weight(
            bssrdf,
            bssrdf_data,
            projection_basis,
            projection_axis,
            incoming_point_prob,
            outgoing_point.get_point(),
            incoming_point.get_point(),
            incoming_point.get_shading_normal());

    // Multiplying the contribution by mis_weight is equivalent to dividing the probability by it.
    incoming_point_prob /= mis_weight;
```
The bug occurs when the sampled axis in `outgoing_point` and the normal of the surface in `incoming_point` are perpendicular. In this case both `mis_weight` and `dot_nn` are equal to zero.

**Comment by Biart95** [comment]
I suggest to add a threshold that would discard such a "bad" incoming points during the tracing of a probe ray. Since the bug essentially comes out of the fact that the probability of the intersection must be 0, it is rather safe merely to remove this kind of intersections.

I will test this approach on many different scenes and see the result.

**Comment by dictoon** [comment]
I don't remember if we discussed that on Slack, but yes, ignoring these incoming points is the right approach.

There used to be a test like the one you describe but it appears to have been lost in the refactorings.

Here it was: https://github.com/appleseedhq/appleseed/blob/4e672d5b98c472a7d247794dc159f8fe79ac916f/src/appleseed/renderer/kernel/lighting/subsurfacesampler.h#L219

**Comment by dictoon** [comment]
@Biart95 @est77: Can we close this issue?

**Comment by Biart95** [comment]
I don't experience NaNs anymore. There are a lot of things to think of when it comes to BSSRDF sampling, but they lay beyond the scope of this issue anyway, so I think we can close it.
@est77 ?

**Comment by dictoon** [comment]
Ok, closing it then, thanks!
