### ISSUE TITLE
Non-robust BeckmannMDF sampling leads to NaN results on some machines

### ISSUE THREAD

**Issue by Biart95** [appleseedhq/appleseed#1347]
## Description

Appleseed build on my machine (Windows 7, Visual Studio 2013, x64) performs badly on **all** scenes with Beckmann, giving a lot of NaN results.

The problem is in microfacet.cpp, in `sample_visible_normals` and in `BeckmannMDF::sample11`.

When `alpha_x` and `alpha_y` are small, `cos_theta` can become 1.0 due to the rounding errors in the following line:
[https://github.com/appleseedhq/appleseed/blob/master/src/appleseed/foundation/math/microfacet.cpp#L140](url) 
The code clearly checks this case while calculating `phi` but for some reason do not check it for `cos_theta`, which in its turn leads to misbehaviour in `BeckmannMDF::sample11`, in the following line:
[https://github.com/appleseedhq/appleseed/blob/master/src/appleseed/foundation/math/microfacet.cpp#L379](url) 
Here `cot_theta` is divided by zero and the bug happens.

## Corresponding chunks of code with comments

In `sample_visible_normals`:
``` c++
    Vector3f stretched(
        sign_cos_vn * v[0] * alpha_x,   //
        sign_cos_vn * v[1],             // <--- alpha_x and alpha_y are small
        sign_cos_vn * v[2] * alpha_y);  //

    stretched = normalize(stretched); // <--- stretched[1] becomes 1.0 due to the rounding errors

    const float cos_theta = stretched[1]; // <--- cos_theta also becomes 1.0, checks provided only for phi
    const float phi =
        stretched[1] < 0.99999f ? atan2(stretched[2], stretched[0]) : 0.0f; 

    // Sample slope.
    Vector2f slope = mdf.sample11(cos_theta, s, gamma); // <--- returns #IND
```

in `BeckmannMDF::sample11`:
``` c++
    const float ct = max(cos_theta, 1.0e-6f);             // <--- 1.0
    const float tan_theta = sqrt(1.0f - square(ct)) / ct; // <--- 0.0
    const float cot_theta = 1.0f / tan_theta;             // <--- INF

    const float c = erf(cot_theta);
```

**Comment by Biart95** [comment]
Clamping cos_theta between `1e-06` and `1.0 - 1e-06` resolves the Issue.

**Comment by dictoon** [comment]
Thanks for the detailed investigation!

@est77 What do you think of the fix proposed by @Biart95?

**Comment by dictoon** [comment]
@Biart95 @est77: Can we close this issue?

**Comment by Biart95** [comment]
I don't experience NaNs anymore. If Esteban agrees, the Issue can be closed.
@est77 ?
