### ISSUE TITLE
Allow filtering unit tests by a regex in appleseed.studio

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1359]

**Comment by htmlboss** [comment]
I've made some progress here but it's a little more complicated than I originally thought. The QTreeWidget that displays all the unit tests cannot be filtered it seems so I've changed it to a QTreeView to allow a custom model. Right now it is repopulated correctly with the parent-children relationship.

Currently I am working on hooking up the checkboxes again and THEN implementing the filtering (which I'm designing to be real-time so the list updates as you change the filter text).

**Comment by htmlboss** [comment]
Just submitted a PR implementing this.

**Comment by dictoon** [comment]
Done.
