### ISSUE TITLE
Test new orthonormal basis construction algorithm

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1367]
Specifically the branchless algorithm from this paper http://jcgt.org/published/0006/01/01/ (listing 3).

It has the potential to be faster than our algorithm (in [`foundation/math/basis.h`](https://github.com/appleseedhq/appleseed/blob/master/src/appleseed/foundation/math/basis.h#L175-L236)).

Also of potential interest: http://jcgt.org/published/0006/01/02/

**Comment by aytekaman** [comment]
I am testing this. I am very interested to see the result of this since I also need a fast basis construction for my own project for my PhD.

**Comment by dictoon** [comment]
Awesome!

We should keep the consistency/accuracy checks that are currently present in our code, because we want a fast but precise algorithm.

**Comment by aytekaman** [comment]
I moved the old basis method back into `basis.h` and made another experiment. New method still performs faster. Actually, this time, it performed even better w.r.t the old one however, i am on a different machine so, this test might not be the most conclusive one. Still, results are consistent and new method seems to be faster according to the benchmarks.

**Comment by dictoon** [comment]
Done.
