### ISSUE TITLE
Optionally limit number of threads in run test suite script

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#1402]
Sometimes you'd like to run the script in the background while doing other things, 
but right now it uses all your cores always.

**Comment by dictoon** [comment]
It's running a single scene at once. What you need to do is instruct appleseed.cli to use fewer cores.

**Comment by est77** [comment]
Yes. We need to add an argument to set the number of cores used when running appleseed.cli.

**Comment by dictoon** [comment]
You can actually pass

    -p="-t 1"

to forward `-t 1` (synonym of `--threads 1`) to appleseed.cli.
