### ISSUE TITLE
Shift+Enter in Python console extends the current line instead of creating a new one

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1474]

**Comment by glebmish** [comment]
what exactly is working wrong?
I tested auto-indentation and execution of script with shift+enter instead of enter. It worked.
Script was:
```
for i in range(10):
    print 'a'
```

**Comment by dictoon** [comment]
It's not about indentation. It's about line numbers:

![image](https://user-images.githubusercontent.com/321290/27772307-a463a456-5f5f-11e7-91f8-c8bdcca2c8dc.png)

**Comment by glebmish** [comment]
Ah, I get it now
