### ISSUE TITLE
It should be possible to vertically resize the Python console's input area

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1479]

**Comment by glebmish** [comment]
Isn't it now? If you pull up the upper bound and pull down the bar between input and output

**Comment by glebmish** [comment]
you can resize it if both log and console opened. If only console opened it behaves exactly like log window. Why would you need to resize it in that case?

**Comment by dictoon** [comment]
I think it would make sense to be able to give more space to the input or output area, instead of fixing both to be half the height of the Python Console panel.

What do you think?

**Comment by dictoon** [comment]
Here's how it looks on my machine:

![image](https://user-images.githubusercontent.com/321290/27582900-e5409082-5b32-11e7-94be-a6dca2631e1d.png)

There is no resize bar between the input and output areas.

**Comment by glebmish** [comment]
I was puzzled because previously I used QSplitter and it was possible to resize. Will add QSplitter again

**Comment by dictoon** [comment]
We should leave this issue open until a fix is merged in master.

**Comment by glebmish** [comment]
Ok, I see
