### ISSUE TITLE
Get rid of WITH_DISNEY_MATERIAL CMake option

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1481]

**Comment by est77** [comment]
We are disabling this build option when building appleseed bundled in Gaffer.
It introduces a dependency SeExpr that is not used in Gaffer or in the Maya and Max plugins.
I'd prefer if we can keep it if it is possible.

**Comment by dictoon** [comment]
Ah ok, I didn't know. Let's keep it then, no problem!
