### ISSUE TITLE
Improve intersections with adjacent surfaces

### ISSUE THREAD

**Issue by Biart95** [appleseedhq/appleseed#1483]
Currently, if two surfaces are very close to each other, `PathTracer` may register intersection only once. This is okay for surface rendring, but can lead to bad results when two volumetric objects are stacked together (because some enter/leave events are missing and media list of ShadingRay contains incorrect media).

**Comment by dictoon** [comment]
This is interesting.

Our handling of intersection precision has historically been very robust. What we cannot guarantee though is to detect intersections with two coincident surfaces. Nested/overlapping volumes should have clearly distinct surfaces.

**Comment by Biart95** [comment]
I apologise if I posted this issue too early. It might be a problem behind the logic of adding/removing media, so it need to be investigated thoroughly.

**Comment by dictoon** [comment]
No problem!

**Comment by Biart95** [comment]
False alarm!

I assumed that if you place three cubes of height 0.333 in coordinates 0.333, 0.666 and 1.000, they will always have a gap of at least 0.001 between them. I was terribly wrong...

Closed in shame.

**Comment by dictoon** [comment]
No worries :)
