### ISSUE TITLE
Proper handling of media priorities in Tracer

### ISSUE THREAD

**Issue by biart** [appleseedhq/appleseed#1484]
We need to ignore the intersections that don't pass medium priority check in `Tracer::do_trace` and `Tracer::do_trace_between` just like we already do that in [pathtracer.h](https://github.com/appleseedhq/appleseed/blob/0b372f6842e3c3c073da4602815550514746f14e/src/appleseed/renderer/kernel/lighting/pathtracer.h#L279).

**Comment by dictoon** [comment]
Good point!

**Comment by psy2d** [comment]
I'd like to work on this issue.

**Comment by psy2d** [comment]
I wanted to confirm my understanding:  for the intersections that don't pass medium priority check, we simply
1. Continue the ray in the same direction.
2. Update the medium list.
3. Trace the ray further.
 Is that right?

**Comment by biart** [comment]
Yes, it is absolutely correct.

**Comment by psy2d** [comment]
Ok thanx!

**Comment by biart** [comment]
See https://github.com/appleseedhq/appleseed/pull/1857 for more details.
