### ISSUE TITLE
Add progressive rendering time limit

### ISSUE THREAD

**Issue by gospodnetic** [appleseedhq/appleseed#1508]
Add an option in studio to use time as a rendering constraint instead of samples per pixel.

**Comment by dictoon** [comment]
It would be nice to have this feature in appleseed.cli as well.

**Comment by Idloj** [comment]
Where is the sample per pixel used as a limit? (my experience is that interactive rendering just runs indefinitely, but maybe I just haven't let it run enough. I think I gave it ~45 minutes)

**Comment by dictoon** [comment]
It's used in the `ProgressiveFrameRenderer` class. The max number of samples is unlimited by default. This setting is not (yet) exposed in the Rendering Settings dialog.

**Comment by Idloj** [comment]
And this issue is about exposing both samples per pixel and time limit in the Rendering Settings?

**Comment by dictoon** [comment]
Yes absolutely!

**Comment by dictoon** [comment]
We should also consider whether we can implement time-limited rendering in final mode.
