### ISSUE TITLE
Saving project crashes if source project files have been deleted

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1517]

**Comment by Idloj** [comment]
Can you detail how to reproduce it? Here's what I've done:

1. Create a new project and save it under some name
2. Delete the project file
3. Save the project again

It didn't crash.

**Comment by dictoon** [comment]
To be honest, I don't recall exactly what the problem was. I should have included detailed repro steps but I was too lazy apparently. I'll close this ticket. We can open it again or create a new ticket if/when we figure it out.

Thanks for looking into it!
