### ISSUE TITLE
Adding a specular coating to glass BSDF darkens output abnormally

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed#1540]
Rendering the glass BSDF is fine, rendering a coating layer separately is also fine. Rendering a coating (ior=1.35), and adding it to a glass BSDF (ior=1.49) however, without any modulating factor and glass BSDF surface transmittance set to 1.0, results in abnormally dark values (one would expect that without any scaling, adding these two closures would break energy conservation).

Glass BSDF only:
![glass1](https://user-images.githubusercontent.com/387352/28246263-78b3a60a-6a48-11e7-9d45-61e6c8ba5212.png)

Dielectric coating over glass BSDF, surface transmittance set to 1.0:
![glass2](https://user-images.githubusercontent.com/387352/28246271-7fc98a9a-6a48-11e7-8194-7ab5f7169662.png)

**Comment by est77** [comment]
Couldn't reproduce the issue.I re-enabled coatings over glass in PR #1893.
We can open a new ticket if this issue appears again.
