### ISSUE TITLE
Wire up OSL's printf() to the renderer's logger

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1617]

**Comment by oktomus** [comment]
You mean mapping `osl_printf ` to the logger ? Or something else ?

**Comment by dictoon** [comment]
Yes exactly, such as `print()` calls in OSL shaders appear in the console or in appleseed.studio's Log panel.

**Comment by oktomus** [comment]
I haven't found much in the OSL source code. It seems that shader print calls are mapped to osl_printf which itself use the default ErrorHandler. I tried to override the default ErrorHandler provider but it hasn't worked. I posted on the OSL mailing list to see if a developer can tell me how they deal with shader functions.

**Comment by dictoon** [comment]
Done.
