### ISSUE TITLE
Linking problem on Archlinux.

### ISSUE THREAD

**Issue by bartoszek** [appleseedhq/appleseed#1625]
I have trouble building Appleseed on archlinux machine.
When procedure gets to linking stage I got bunch of those warnings.
```
libappleseed.so: undefined reference to `typeinfo for OSL::RendererServices'
```
`libappleseed.so` builds fine, and it shows correct imported symbols with `ldd -D`.
Is this issue related to OSL version or is it my fault. 
cmake flags: 
```
-- Cache values
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;Profile;Ship
CMAKE_INSTALL_PREFIX:PATH=/usr/local
HIDE_SYMBOLS:BOOL=ON
OSL_COMPILER:FILEPATH=/usr/bin/oslc
OSL_MAKETX:FILEPATH=/usr/bin/maketx
OSL_QUERY_INFO:FILEPATH=/usr/bin/oslinfo
QT_QMAKE_EXECUTABLE:FILEPATH=/usr/bin/qmake-qt4
USE_AVX:BOOL=ON
USE_AVX2:BOOL=ON
USE_EXTERNAL_EXR:BOOL=ON
USE_EXTERNAL_OCIO:BOOL=ON
USE_EXTERNAL_OIIO:BOOL=ON
USE_EXTERNAL_OSL:BOOL=ON
USE_EXTERNAL_PNG:BOOL=ON
USE_EXTERNAL_SEEXPR:BOOL=ON
USE_EXTERNAL_XERCES:BOOL=ON
USE_EXTERNAL_ZLIB:BOOL=ON
USE_SSE:BOOL=ON
USE_SSE42:BOOL=ON
USE_STATIC_BOOST:BOOL=OFF
USE_STATIC_OCIO:BOOL=OFF
USE_STATIC_OIIO:BOOL=OFF
USE_STATIC_OSL:BOOL=OFF
USE_VISIBILITY_MAP:BOOL=OFF
WARNINGS_AS_ERRORS:BOOL=OFF
WITH_CLI:BOOL=ON
WITH_DISNEY_MATERIAL:BOOL=ON
WITH_PYTHON:BOOL=ON
WITH_STUDIO:BOOL=ON
WITH_TOOLS:BOOL=ON
```
package versions:
gcc 7.2.0-1
cmake 3.9.2-2
openshadinglanguage 1.7.5-2

**Comment by est77** [comment]
This happens because LLVM and probably OSL too, are built with RTTI disabled.
You need to recompile them with RTTI enabled and then libappleseed.so will link correctly.

**Comment by bartoszek** [comment]
Seems this way, looking at output of `nm -CD /usr/lib/liboslexec.so` there is no `typeinfo` only `vtable`.
Thanks for the tip @est77

**Comment by est77** [comment]
Yes, this is one of the most common problems. We do use RTTI in appleseed, so disabling it is not an option.

**Comment by bartoszek** [comment]
Ok, appending `-DENABLERTTI=ON` to OSL cmake build invocation fixes the problem.

**Comment by dictoon** [comment]
@bartoszek Cool!
