### ISSUE TITLE
Add support for shutter opening curves to camera

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1681]
For reference, see https://rmanwiki.pixar.com/display/RFM/Motion+Blur+in+Maya, "Shutter Opening" section.

**Comment by Narann** [comment]
Maybe [a start point](https://github.com/appleseedhq/appleseed/blob/c564d4f1e5055a33e35c2c03efef487736dbf748/src/appleseed/renderer/kernel/shading/shadingray.h#L224).

**Comment by dictoon** [comment]
The change is likely to take place in `renderer::Camera::initialize_ray()`:

    sampling_context.split_in_place(1, 1);
    ray.m_time =
        ShadingRay::Time::create_with_normalized_time(
            sampling_context.next2<float>(),
            m_shutter_open_time,
            m_shutter_close_time);

The idea is to map `sampling_context.next2<float>()` to the desired curve before passing it to `ShadingRay::Time::create_with_normalized_time()`.

**Comment by Narann** [comment]
I want to point [what RenderMan do](https://rmanwiki.pixar.com/display/REN/Shutter) because I think it's the more evolved and interesting.

**Comment by dictoon** [comment]
That's rather awesome :)

**Comment by pjessesco** [comment]
Hey I'd like to try this issue.

**Comment by dictoon** [comment]
Definitely, go for it!

**Comment by pjessesco** [comment]
@dictoon link is dead :(

**Comment by dictoon** [comment]
@pjessesco They keep changing their links, it's annoying. Here: https://rmanwiki.pixar.com/display/RFM/Motion+Blur+in+Maya

**Comment by dictoon** [comment]
@fedormatantsev @pjessesco I think we can consider this done now that we support linear and Bézier opening/closing curves. What do you think?

**Comment by fedormatantsev** [comment]
@dictoon agree.
