### ISSUE TITLE
Small improvements to custom OSL nodes

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed#1695]
Remove unnecessary normalize calls, these are not needed since normals are already unit length in OSL. The same applies to the viewer vector I.
We now have hashnoise(), so the maya value noise calls can use this, which should speed things up a bit.

**Comment by dictoon** [comment]
@luisbarrancos What's the status no this?

**Comment by luisbarrancos** [comment]
Unnecessary normalize calls removed with 8764d71472663fa87f8126251f63c5e50ac536ea and noise improvements via hashnoise() added with https://github.com/appleseedhq/appleseed/pull/2128
I think this can be closed.
