### ISSUE TITLE
Minor UI artifacts when squeezing Tests dialog

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1719]
The button at the bottom left of the dialog are cropped:

![image](https://user-images.githubusercontent.com/321290/33046088-c49b86ee-ce4f-11e7-9e14-4f09ff12884a.png)

**Comment by qq456cvb** [comment]
This can be resolved by setting minimum size of the left panel or automatic hide button texts and replace them with "..." like "Check onl...". What do you think?

**Comment by dictoon** [comment]
The solution of setting a minimum size makes much more sense, and I see that it's the one you implemented. Thanks!

**Comment by dictoon** [comment]
Fixed.

**Comment by qq456cvb** [comment]
Although the minimum widths for left(350) and right(300) panels specified in the patch is safe for MacOS, it's not safe for windows.

![tim 20180329121736](https://user-images.githubusercontent.com/7703989/38069847-31340974-334b-11e8-909a-75c293802fd6.png)

I think 400 and 320 are safe widths for both Windows and MacOS. I do not have a build for Linux, if it is also safe, I will issue a PR.

**Comment by dictoon** [comment]
Can you open a PR and set widths to the values you suggested?

**Comment by qq456cvb** [comment]
Sure.
