### ISSUE TITLE
Allow setting negative exposures e.g. in lat-long environment EDF

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1727]

**Comment by rgirish28** [comment]
Does this mean just being able to move the slider to <0 as you can set the exposure in lat-long edfs to negative values in the text field. Also, do you want to set the default slider position for lat-long edfs to have a range from -ve to +ve like diffuse edf? I hope my questions are clear?

**Comment by dictoon** [comment]
This ticket is not only about environment EDFs, it's about exposures in general: wherever there is an exposure parameter, it should be possible to specify a negative exposure value, either by typing the value directly, or by moving the slider. The slider's defaut range should probably be symmetric around 0 to readily allow negative values.

**Comment by rgirish28** [comment]
Ah ok. I've fixed the issue through #1886 by first fixing the slider range in colormaps and then set the slider to be symmetric around zero for exposure fields. The exposure fields with numeric inputs have slider bars that are already symmetric around 0. I hope this is what you want. However, the travis build gets timed out for gcc 6.

**Comment by dictoon** [comment]
@rgirish28 What's the status on this?

**Comment by rgirish28** [comment]
I think this issue can be closed as we have merged the fix through #1886. The build timing out also was fixed before merging.

**Comment by dictoon** [comment]
Thanks!
