### ISSUE TITLE
Disallow changing diagnostic modes during final rendering

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1728]

**Comment by est77** [comment]
We are using the diagnostic modes in appleseed.maya and gafferseed both for final and progressive renders.
I think they are useful for turntables and to debug problems in scenes. I'd prefer to keep them.

**Comment by dictoon** [comment]
Sorry, my description isn't very clear. I simply meant that it shouldn't be possible to enable or change diagnostic modes _during final rendering in appleseed.studio_.

**Comment by dictoon** [comment]
Done in #2353.
