### ISSUE TITLE
Update OSL to 2.0

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed#1730]
There is work underway requiring the new hash(), hashnoise() calls (stdosl.h)

**Comment by luisbarrancos** [comment]
WIP at
https://github.com/luisbarrancos/appleseed/commit/da37c851addc0399df0e7ba429bb7f3e7a14e4a6
https://github.com/luisbarrancos/appleseed/commit/15eb25cb155b78ac6b23077276428d1c28e6c3ff

**Comment by est77** [comment]
On linux, since 2.0 we bundle OSL 1.9.8. I had to update to LLVM 5.0.1 because 3.4 was crashing on newer intel CPUs.

**Comment by luisbarrancos** [comment]
At this point in time and considering we're supporting OIIO 2.0 and moved to at least LLVM 5.x, OSL will most likely be RB-2.0/2.0 branch.

**Comment by dictoon** [comment]
I would suggest sticking to 1.10 as 2.0 is not available at this time.

**Comment by dictoon** [comment]
Done via https://github.com/appleseedhq/appleseed-deps/pull/6 and https://github.com/appleseedhq/appleseed/pull/2594.
