### ISSUE TITLE
Use OIIO for image output

### ISSUE THREAD

**Issue by predat** [appleseedhq/appleseed#1732]
As appleseed already uses OpenImageIO for texture reading, it could be beneficial to use this library also for writing image output from the renderer. So, we could also use any image format already available in OpenImageIO for writing image.
I know it's a lot of work but who knows...

**Comment by dictoon** [comment]
Agreed! It's really not that much work, I think it can be wrapped in an hour or two.

**Comment by Blackhart** [comment]
Definitively interested to implement it!

**Comment by dictoon** [comment]
Sure, by all means please do!

**Comment by dictoon** [comment]
I'm assigning you the issue so that we avoid effort duplication.

**Comment by est77** [comment]
Done in 0e0f7cb97db2a7ce8ef43e5180c9ef3bf5fa030c
