### ISSUE TITLE
Update demo scenes

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1739]
Some demo scenes such as Emily are not compatible with the latest official release of appleseed (1.8.0-beta). For example they may rely on the Microfacet BRDF which was removed.

**Comment by zohozer** [comment]
The "Rose" one crashes the Appleseed 1.8.0-beta.

**Comment by dictoon** [comment]
@zohozer Thanks. Can reproduce. Investigating what's going on.

**Comment by dictoon** [comment]
All scenes are fixed and links are up-to-date on the Download page.

**Comment by zohozer** [comment]
Still are fixes to do.

The "fluffy_cornell_box" don't have geometry. All the files in the geometry folder are .txt files.

Also you need to mention that this files will work only with the latest 1.8 version of Appleseed.

**Comment by dictoon** [comment]
I just tested the Fluffy Cornell Box scene that's available for download on the site and it works fine (see remark below though). The geometry in the `geometry` folder is of two kinds: *.obj files for the Cornell Box and *.txt files for the curves (for which we don't have a good file format yet).

Can you check again?

> Also you need to mention that this files will work only with the latest 1.8 version of Appleseed.

Good point.

Remark concerning the Fluffy Cornell Box scene: appleseed 1.8.0-beta has a bug where the Max Ray Intensity only works partially, this leads to fireflies in the rendering. We'll issue a hot fix shortly.

**Comment by zohozer** [comment]
On the bottom right image you can see the old geometry folder.
 
![fluffybox_zip](https://user-images.githubusercontent.com/5983791/33515950-faa68b60-d761-11e7-9e04-dad1a4702a59.png)
![fluffybox_geometry](https://user-images.githubusercontent.com/5983791/33515951-fac35df8-d761-11e7-8c36-5d253129ed9f.png)

Also will be good to keep the old files for testing with older releases.

Personally I can't open the new files. I'm on Mac and I can run only Appleseed 1.7 here. Any news about the 1.8 release for Mac?

**Comment by zohozer** [comment]
I just realised that this "curves" files are huge in size? 51.6MB for a simple quad mesh?

**Comment by dictoon** [comment]
I just added the clarification you suggested on the download page: https://appleseedhq.net/download.html

Regarding the Fluffy Cornell Box scene:

I see that you're using the scene from the repo. We're omitting the geometry assets intentionally as they are way too large for GitHub (not in the specific case of that scene of course, but generally speaking). It's a bug that the curve files are part of the repo, I'll remove them.

You should download the test scenes available from the Download page, or from the Releases page on GitHub.

appleseed 1.8.0-beta is available for OS X Yosemite and older but it currently requires a 64-bit CPU with SSE4.2 support. I just realized you're the same person who reported that problem on our forum. I'll try to make a macOS build that doesn't require SSE4.2 over the week-end but it's a very long and complicated task unfortunately.

**Comment by zohozer** [comment]
Ok. Thank you for clarification.

Seems that my CPU have SSE4.2 support. I'm on Sierra 10.12.6.

Here is the output of the capabilities of my CPU:

$ sysctl -a | grep machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C

**Comment by dictoon** [comment]
Regarding the large size of curves files: these are totally unoptimized text files. It's a temporary format until appleseed gains proper support for Alembic files.

Regarding your CPU: we investigated the problem quite a bit and it looks like one of the third party library we're depending on uses some advanced instructions that aren't necessarily available on all SSE4.2-enabled CPUs.

**Comment by zohozer** [comment]
Ok. Thank you, now I understand.
