### ISSUE TITLE
Investigate perf regression when navigating during interactive rendering

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1743]
A good starting point is to instrument the time it takes to run `on_render_begin()`, `on_frame_begin()`, `on_render_end()` and `on_render_end()`.

**Comment by aytekaman** [comment]
I investigated this a bit. Is this issue can be related to display transforms?

**Comment by dictoon** [comment]
Good question. I was under the impression there was a slowdown even if `None` was chosen as a display transform (which ideally shouldn't incur any performance penalty compared to before).

**Comment by aytekaman** [comment]
Is there a known commit that does not have this problem? I might be able to bisect it if my poor laptop agrees:)

**Comment by dictoon** [comment]
I would recommend first trying the official versions of appleseed (1.7.0 or 1.7.1 vs 1.8.0). If you can confirm that this performance regression is real and indeed not due to display transforms, then I can help you find potential culprits.

**Comment by aytekaman** [comment]
I checked latest releases and the master. There isn't a noticeable difference (in fact they all feel same to me) between those versions when `None` is chosen as a display transform. Could you check it again? If there is a difference, I will try to measure the performance in a more formal way as you suggested.

**Comment by dictoon** [comment]
Thanks for checking. I might have had a display transform then. Since you haven't identified any obvious slowdown without a display transform, I think it's reasonable to close this ticket. Thanks again!
