### ISSUE TITLE
basic.cpp sample fails to link on Linux?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1759]
Reported by @naseef:

    /usr/bin/ld: CMakeFiles/basic.dir/basic.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'

Doesn't happen with the other C++ samples.

**Comment by est77** [comment]
appleseed/1.9.0/include/renderer/modeling/entity/entityfactoryregistrar.h:48:32: fatal error: boost/filesystem.hpp: No such file or directory
 #include "boost/filesystem.hpp"

**Comment by est77** [comment]
Related to #1765 

Removed boost filesystem dependency in #1763

**Comment by dictoon** [comment]
@est77 Can we close this issue?
