### ISSUE TITLE
Can't compile bcd project with VS2012

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed#1786]
Hi,
I think `=default` keyword is not supported in vs2012.
After I removed all default-s, just to check if everything else is fine, it says:
```
Denoiser.cpp(258): error C2039: 'isnan' : is not a member of 'std'
Denoiser.cpp(258): error C2873: 'isnan' : symbol cannot be used in a using-declaration
Denoiser.cpp(259): error C2039: 'isinf' : is not a member of 'std'
Denoiser.cpp(259): error C2873: 'isinf' : symbol cannot be used in a using-declaration
Denoiser.cpp(274): error C3861: 'isnan': identifier not found
Denoiser.cpp(274): error C3861: 'isinf': identifier not found
```
I've tried `#include <cmath>` and `#include <math.h>` but it didn't help for some reason.

**Comment by usakhelo** [comment]
Also `snprintf()` couldn't be found in `ImageIO.cpp`.
I've tried to replace it with `_snprintf()`. I don't think this is correct since this is probably Microsoft only thing.

**Comment by dictoon** [comment]
Good catch.

We can replace:

* `std::isnan()` by `foundation::FP<float>::is_nan()` or `foundation::FP<double>::is_nan()` (`foundation/math/fp.h`)
* `std::isinf()` by `foundation::FP<float>::is_inf()` or `foundation::FP<double>::is_inf()`
* `std::snprintf()` by `foundation::portable_snprintf()` (`foundation/platform/snprintf.h`)

**Comment by est77** [comment]
Fix attempt here: a1234a92dd745337f7e70eff1a13c634d9196fa8

**Comment by usakhelo** [comment]
Checking...

**Comment by usakhelo** [comment]
DenoisingUnit.cpp(55): error C2220: warning treated as error - no 'object' file generated
DenoisingUnit.cpp(55): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
DenoisingUnit.cpp(57): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
Denoiser.cpp(125): error C2661: 'std::thread::thread' : no overloaded function takes 8 arguments
Denoiser.cpp(179): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
Denoiser.cpp(329): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
Denoiser.cpp(341): error C2039: 'isnan' : is not a member of 'std'
Denoiser.cpp(341): error C2873: 'isnan' : symbol cannot be used in a using-declaration
Denoiser.cpp(342): error C2039: 'isinf' : is not a member of 'std'
Denoiser.cpp(342): error C2873: 'isinf' : symbol cannot be used in a using-declaration

**Comment by est77** [comment]
I updated the commit with the fix

**Comment by usakhelo** [comment]
There's one more `conversion from 'size_t' to 'int'` on line 183:
`newPercentage = (i_nbOfPixelsComputed * 100) / i_totalNbOfPixels;`
And I had to add `#define _VARIADIC_MAX 8` before standard headers. Looks like by default it accepts 5 args - https://stackoverflow.com/a/9153936/240804

**Comment by est77** [comment]
Thanks for checking. I'll fix them and update the PR

**Comment by usakhelo** [comment]
Great! It's working now.
