### ISSUE TITLE
Typing values in color entity's Color field doesn't update color preview

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1789]

**Comment by jaykay12** [comment]
![screenshot from 2018-02-14 22-59-15](https://user-images.githubusercontent.com/13948542/36218569-d88bd50e-11da-11e8-91a8-404ab72f1ab8.png)


If I am not wrong, the color preview containing bug is this one, its not updating when I am changing the RGB value in the input field.

**Comment by dictoon** [comment]
@jaykay12 That's correct.

**Comment by jaykay12** [comment]
Okayy @dictoon thanks for confirming.
I will be trying to resolve this one once my sessionals are over in just couple of days.

**Comment by dictoon** [comment]
Done.
