### ISSUE TITLE
Let frame/tile/pixel engines print their parameters when rendering starts

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1804]

**Comment by psy2d** [comment]
Hey I'd like to take up this issue. I'm new to open source. It would be great if you could help me get started.
I'm comfortable with C++ and I have built appleseed on my machine.

**Comment by oktomus** [comment]
I will try to do it for my first contribution :)

**Comment by oktomus** [comment]
I found where to print the settings (`Frame::print_settings` or in `IRendererController::Status MasterRenderer::initialize_and_render_frame_sequence()`) but what exactly do you have in mind ?

**Comment by dictoon** [comment]
`Frame::print_settings()` is the frame printing its settings. We want other key modules (`IFrameRenderer`, `ITileRenderer`, `IPixelRenderer`, `ISampleRenderer` and derived classes) to be able to print their settings when rendering starts. Once the infrastructure is in place we can discuss which settings should be displayed, but as a rule of thumb anything that the user can set should have end up being visible in logs.

**Comment by oktomus** [comment]
Ok thanks for the details :)

**Comment by oktomus** [comment]
This can be closed :)

**Comment by dictoon** [comment]
Indeed, thanks man!
