### ISSUE TITLE
appleseed crashes when mouse is dragged out of canvas if the pixel inspection is toggled on

### ISSUE THREAD

**Issue by aytekaman** [appleseedhq/appleseed#1817]
It seems that `DragLeave` event is not fired when mouse is dragged out of the canvas. Then, pixel inspector tries to access pixels outside of the canvas which results in a crash. Can anyone reproduce the crash?

**Comment by dictoon** [comment]
Well spotted, I can reproduce. I'll look into it.

**Comment by dictoon** [comment]
Indeed, from the [Qt 4.8 docs](http://doc.qt.io/archives/qt-4.8/qwidget.html#underMouse):

```
bool QWidget::underMouse() const
```

Returns true if the widget is under the mouse cursor; otherwise returns false.

This value is not updated properly during drag and drop operations.

**Comment by aytekaman** [comment]
There is one minor annoyance. When the cursor is dragged out of the canvas, tooltip does not disappear as it does when the mouse is not pressed. I am fixing this now.

**Comment by dictoon** [comment]
I had noticed it but decided to live with it. Thanks for fixing the problem :)

**Comment by aytekaman** [comment]
Yes it was very very minor issue:) You are welcome.
