### ISSUE TITLE
Emit warning when shutter times are inconsistent

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1838]
In particular when shutter times are not properly ordered (shutter open begin < shutter open end < shutter close begin < shutter close end).

**Comment by fedormatantsev** [comment]
I could get this one alongside with shutter curve feature. Please assign this one to me.

**Comment by pjessesco** [comment]
Isn't it done?

**Comment by dictoon** [comment]
It is, yes. Good catch!
