### ISSUE TITLE
Significant difference in render times between OSL and built-in

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#1841]
Set up a scene with a mix of two Disney nodes lit by an HDRI.  Each material has three texture maps driving different parameters.  With built_in shaders and the original JPEG textures the render took about 1:17.  With OSL and .tx files it took 8:30.  That is a huge difference that doesn't seem justified by the setup.  It is definitely something to do with the texture sampling as without textures there is still a delta but it is only about 5-7 seconds as opposed to 4x longer

https://drive.google.com/open?id=1S2zSaw6WMgI1fAf6mWqxcuHfncK2ZosE
https://drive.google.com/open?id=19MyYYfv12zV0at59BeewSD6Tv6H_6ZWs

**Comment by dictoon** [comment]
Fixed by https://github.com/appleseedhq/appleseed-deps/commit/b480c79f7d4e651d5bb36c9b10d7deb5fae9e2c4
