### ISSUE TITLE
Change default number of diffuse bounces to 3 in appleseed.studio

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1848]

**Comment by abhayjindal51** [comment]
Hello @dictoon , 
I would like to work on this issue

**Comment by rgirish28** [comment]
So do you want the maximum diffuse bounces to be set to 3 as default in render settings? Just making sure. Thanks.

**Comment by dictoon** [comment]
That's correct. There are unfortunately a couple places where the default value appears: in the render settings, but also when retrieving max bounce parameters from a render configuration.

**Comment by rgirish28** [comment]
This issue can be closed now :)

**Comment by dictoon** [comment]
Let's keep it open until the default is _indeed_ changed to 3; right now the default is still unlimited, it only becomes 3 (instead of 8) when unlimited is unchecked.

**Comment by rgirish28** [comment]
Default changed for real! #1891

**Comment by juancarlosgzrz** [comment]
Done!

**Comment by dictoon** [comment]
It doesn't appear to be working as expected, default is still unlimited:

![image](https://user-images.githubusercontent.com/321290/37553114-a16b4524-29c1-11e8-9a5f-c7a09e91a220.png)

**Comment by dictoon** [comment]
It's not done:

![image](https://user-images.githubusercontent.com/321290/37553126-d573d534-29c1-11e8-8510-6c1b27fc5111.png)

It will be done when https://github.com/appleseedhq/appleseed/pull/1891 is merged.
