### ISSUE TITLE
Fix saving of adaptive sampler's diagnostic AOVs

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1858]
They exist as "extra AOV images" created by `Frame::create_extra_aov_image()` but they aren't saved to disk by `Frame::write_aov_images()` or `Frame::write_main_and_aov_images()` since they aren't backed by AOV entities.

**Comment by oktomus** [comment]
You can assign me if that's ok :)

**Comment by oktomus** [comment]
This can be closed :)

**Comment by dictoon** [comment]
Yes, thanks!
