### ISSUE TITLE
Allow sending AOV tiles to stdout

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1882]

**Comment by oktomus** [comment]
Being able to print tiles boundaries while rendering or printing each tile rendered output ?

**Comment by dictoon** [comment]
The goal here is to send the actual AOV tiles _pixels_ to stdout (configured to use binary format). Check the file appleseed.cli/stdouttilecallback.cpp.

**Comment by oktomus** [comment]
Thanks, I will have a look!

**Comment by dictoon** [comment]
Fantastic! The goal is to send AOV tiles to blenderseed, our Blender plugin. Feel free to discuss the Blender side of things with @jdent02 on #blenderseed.
