### ISSUE TITLE
Missing extension in recent projects

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#1885]
Try this:
- Save the project to a location without specifying manually the `.appleseed` extension
- Your project is correctly saved as a `.appleseed` file
- Checkout `File > Open recent`
- You will see your project but without the `.appleseed` extension, and that can't be opened.

If you manually specify the extension, there isn't any problem.

**Comment by dictoon** [comment]
Good catch! I tagged the issue. Do you have access to tags?

**Comment by oktomus** [comment]
No I don't :/
