### ISSUE TITLE
Fix cameras' print_settings()

### ISSUE THREAD

**Issue by pjessesco** [appleseedhq/appleseed#1892]
It should print `shutter_open_end` and `shutter_close_start`.

**Comment by pjessesco** [comment]
@dictoon Isn't it related with other cameras?

**Comment by dictoon** [comment]
You're completely right.

**Comment by slongle** [comment]
Does it is just the change from "shutter open" to "shutter_open_end" and "shutter close" to "shutter close start"? 
If so, it need to change the code in src/appleseed/renderer/modeling/camera/

- "thinlencamera.cpp" at 558, 559 line
- "sphericalcamera.cpp" at 213, 214 line
- "orthographiccamera.cpp" at 253, 254 line
- "pinholecamera.cpp" at 287, 288 line

**Comment by slongle** [comment]
You mean `shutter_open_end` is different from `shutter open`?

**Comment by pjessesco** [comment]
Yes it is!
