### ISSUE TITLE
Rename SSS Ray Depth in as_subsurface

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1898]
Maybe SSS Depth? How is it called in other renderers?

**Comment by juancarlosgzrz** [comment]
SSS Depth is fine. Is it really needed to expose this  parameter? in which cases would you need to use this?

**Comment by dictoon** [comment]
It's an performance tuning parameter: it's the number of bounces after which SSS is approximated by diffuse. The lower the faster, the higher the more accurate.

**Comment by luisbarrancos** [comment]
Are we sure we want to rename it to SSS depth? The first thing that comes to mind with SSS depth is probably the image of light entering a certain depth of the object volume upon which it starts scattering. With ray depth we're unequivocal.

**Comment by dictoon** [comment]
You're right, in retrospect that seems like a bad idea.

**Comment by luisbarrancos** [comment]
Closing this ticket then.
