### ISSUE TITLE
appleseed.studio - Custom plugins not loading on Linux

### ISSUE THREAD

**Issue by szczepaniak-bartek** [appleseedhq/appleseed#1921]
Hi,
I was going to test the _distance field object_ from samples/cpp. I've build the lib, put it to `/opt/appleseed/studio/plugins/distancefieldobject.so` but studio keep throwing an error: `while defining object: invalid model "distance_filed_object"`.
_strace_ shows only stats call: 
`stat("/opt/appleseed/studio/plugins/infiniteplaneobject.so", {st_mode=S_IFREG|0755, st_size=133000, ...}) = 0`
Sys info: archlinux (4.15); gcc (7.3); boost (1.66); osl(1.9.7); appleseed (1.8.1.beta.r255.g3decc2e6a)
What am I doing wrong?

**Comment by dictoon** [comment]
There's a typo in `distance_filed_object`, are you sure it's not simply that?

**Comment by szczepaniak-bartek** [comment]
Nope, just my typo. Here is `log` from the console.
[asr.log](https://github.com/appleseedhq/appleseed/files/1828700/asr.log)
I was _scouting_ the code, to find out how the `search_paths` is defined for Linux, maybe putting appleseed to /opt/ messing out the objectfactory loader :?

**Comment by dictoon** [comment]
Ah, it simply didn't find your plugin. Try setting the `APPLESEED_SEARCHPATH` environment variable (a collection of paths separated by `:` on Linux).

**Comment by dictoon** [comment]
Another solution is to edit the project file and add this right after `<project>`:
```
<search_paths>
    <search_path>
        /search/path/one
    </search_path>
    <search_path>
       /search/path/two
    </search_path>
</search_paths>
```

**Comment by dictoon** [comment]
You can also set the logging verbosity to `debug` by editing `settings/appleseed.studio.xml` (the next version of appleseed.studio has a proper Settings dialog).

**Comment by szczepaniak-bartek** [comment]
Thank you very much, exactly what I was looking for!
