### ISSUE TITLE
Write a Python program to parse Light Paths files

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1946]
Write a small standalone Python program to parse and display the content of Light Paths files. The format of Light Paths file is documented at https://github.com/appleseedhq/appleseed/wiki/Light-Paths-File-Format.

Sample Light Paths file: [sample.aspaths.zip](https://github.com/appleseedhq/appleseed/files/1866455/sample.aspaths.zip)

**Comment by idietmoran** [comment]
Do you want the contents displayed in a human readable format?  
If so, how do you want the output formatted?

```
[ASPATHS]
[VERSION]
01
[PATHS]
0020
```
or would you prefer a json?

**Comment by dictoon** [comment]
I was initially thinking about just dumping info in a human format but an `*.aspaths` to `*.json` converter seems like a wonderful idea!!

**Comment by idietmoran** [comment]
Here's my proposed json format

```json
{
    "signature": "ASPATHS",
    "version" : 1,
    "paths": 100,
    "width": 50,
    "heigth": 40,
    "index": [
        {
            "offset": 8,
            "paths": 2
        },
        {
            "offset": 10,
            "paths": 5
        }
    ],
    "nameTable": {
        "number": 2,
        "names": [
            {
                "length" : 3,
                "name": "foo"
            },
            {
                "length": 3,
                "name": "bar"
            }
        ]
    },
    "lightPaths": {
        "x" : 20.1,
        "y" : 22,
        "number": 24,
        "vertices" : [
            {
                "index": 0,
                "x": 20.5,
                "y": 120.6,
                "z": 30.2,
                "red": 250,
                "green": 120,
                "blue": 0
            },
            {
                "index": 0,
                "x": 20.5,
                "y": 120.6,
                "z": 30.2,
                "red": 250,
                "green": 120,
                "blue": 0
            }
        ]
    }
}
```

I will get to work on it when I get home.

**Comment by dictoon** [comment]
Looks great!

I'm in a hurry now but I'd suggest a few simplifications:

    {
        "version" : 1,
        "paths": 100,
        "width": 50,
        "heigth": 40,
        "index": [
            {
                "first": 8,
                "count": 2
            },
            {
                "first": 10,
                "count": 5
            }
        ],
        "nameTable": [ "foo", "bar" ],
        "lightPaths": [
            {
                "x": 20.1,
                "y": 22.3,
                "vertices": [
                    {
                        "objectName": 0,
                        "position": [ 20.5, 120.6, 30.2 ],
                        "radiance": [ 250.3, 120.1, 0.1 ]
                    },
                    {
                        "objectName": 1,
                        "position": [ 20.5, 120.6, 30.2 ],
                        "radiance": [ 250.3, 120.1, 0.1 ]
                    }
                ]
            }
        ]
    }

Note that RGB components are floating point values.

Thanks!

**Comment by idietmoran** [comment]
Yes, thank you for the simplifications! I will get to work when I can, this should be fairly straight forward.

**Comment by idietmoran** [comment]
Because I do not have data to test against, I want to ensure I am doing this correctly. For paths (4 bytes) I get a `[0b11001000, 0b1101001, 0b0, 0b0]`, so I assume the proper number is `0110100111001000` which is equal to `27080` in decimal.  I understand it's little endian, but I want to ensure that this process is correct.

**Comment by idietmoran** [comment]
When you get a chance could you send me a different sample file?

**Comment by dictoon** [comment]
27080 sounds right for the number of paths. I think you'll quickly know if you're assembling bytes in the right order when you'll come to parse floating point values.
