### ISSUE TITLE
Integrate Cryptomatte

### ISSUE THREAD

**Issue by Blackhart** [appleseedhq/appleseed#1962]
> Cryptomatte is a tool created at Psyop by Jonah Friedman and Andy Jones. It creates ID mattes automatically with support for motion blur, transparency, and depth of field, using organizational information already available at render time. This organizational information is usually names, object namespaces, and material names.

[Sources](https://github.com/Psyop/Cryptomatte)  from Psyop's github repository.

**Comment by est77** [comment]
Also worth checking out is Cryptomatte: https://github.com/Psyop/Cryptomatte

**Comment by Blackhart** [comment]
I'm assigning me this issue.

**Comment by dictoon** [comment]
Done in #2352.
