### ISSUE TITLE
Check that C++ samples/plugins compile

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1983]

**Comment by dictoon** [comment]
Checked on Windows, all plugins build and work correctly.

**Comment by jsxs0** [comment]
Can we still work on this issue, or is it closed?

**Comment by jsxs0** [comment]
> 
> 
> Checked on Windows, all plugins build and work correctly.

Can we still work on this issue, or is it closed?

**Comment by dictoon** [comment]
It's been closed on April 21, 2018.
