### ISSUE TITLE
Make sure that Energy Compensation is 1 by default everywhere

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2020]
Changing the default value must be done without breaking compatibility.

In a second step, we will decide whether or not EC should be exposed to users in the plugins.

**Comment by est77** [comment]
We need to check what happens in the MetalBRDF if the user inputs non-physical values.
I am not sure if the result is correct in this case.

**Comment by luisbarrancos** [comment]
The following shaders are affected: blackbody, metal, subsurface.
Blackbody does not expose this to the user, and EC is hardcoded in the closure call to 1.0.
The specular term in the subsurface shader does the same thing - parameter is **not** exposed to the user, and EC is hardcoded to 1.0.
The only case where EC is exposed is in the metal shader - it was mostly for @est77 to have a easy way to compare with/without EC tables in appleseed-maya.
To conclude - only the metal shader exposes this to the user, and this is to be hidden.
I can add *widget=null* at the moment - this will not expose it, but it will not break existing connections from existing scenes. What do you think?

**Comment by luisbarrancos** [comment]
Done with https://github.com/appleseedhq/appleseed/pull/2128
