### ISSUE TITLE
What's the purpose of Animate checkbox in noise shaders?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2033]
Here in `as_noise3d` in 3ds Max:

![image](https://user-images.githubusercontent.com/321290/39770139-7eb5495c-52ee-11e8-9707-d1316efb7c98.png)

Why can't it be always checked?

Can you check it and hide it?

**Comment by luisbarrancos** [comment]
@dictoon it was this
[discussion](https://groups.google.com/forum/#!searchin/osl-dev/frame%7Csort:date/osl-dev/0u8Nhayacwk/03gVxzfHCAAJ)
and the attribute is ```camera:frame``` but we don't support it yet.

**Comment by est77** [comment]
If the user wants OSL's frame then he / she should fetch it from OSL attributes and pass it to the noise shader.

**Comment by luisbarrancos** [comment]
@est77 you mean via getattribute and the attributes node? If so i'll update the as_attribute node once the *frame* PR is merged.

**Comment by luisbarrancos** [comment]
@est77 That's *frame time*. Perhaps relabelling it to *time* would suffice. I'm ok removing the *scale*, perhaps the checkbox as well, and just test the input for anything other than 0 or an input connection.

**Comment by luisbarrancos** [comment]
Done with https://github.com/appleseedhq/appleseed/pull/2128
