### ISSUE TITLE
Allow collapsing Advanced section in Rendering Settings dialog

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2044]

**Comment by takaiten** [comment]
@dictoon, is this issue still available? I would like to try to solve it

**Comment by dictoon** [comment]
Go ahead.

**Comment by takaiten** [comment]
Didn't worked with Qt for a long time, hope it works as you wanted.
Also I'd love to work with all of you this summer at GSoC. Tomorrow I'll introduce myself in Discord.

**Comment by dictoon** [comment]
Done, thanks for your contribution!
