### ISSUE TITLE
Fix render tile frame highlighting

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/appleseed#2051]
Render tile frame highlighting does not work anymore after some recent code changes.

**Comment by est77** [comment]
In appleseed.maya, tile highlighting  is disabled because of some bugs with high number of threads.
I'd like to enable it back at some point.

**Comment by Mango-3** [comment]
@dictoon  You are right, it's not an appleseed issue. I saw it not working in the plugins (in Max it works though) and thought otherwise. You may close the ticket then.
