### ISSUE TITLE
Building on Windows with alternative CMake generators

### ISSUE THREAD

**Issue by boberfly** [appleseedhq/appleseed#2059]
Hi all,

I've been trying to build Appleseed with a different generator on Windows (specifically either "Ninja" or "NMake Makefiles JOM") but I've got one issue here:
[win-vs.txt](https://github.com/appleseedhq/appleseed/blob/master/cmake/config/win-vs.txt#L396)

I'm guessing ${TargetPath} is an MSTarget-specific variable? Can I change this so that it's like the other ones? Eg.
`get_target_property (target_path ${target} LOCATION)`
Or will this break Visual Studio/MSTarget?

Cheers!

**Comment by boberfly** [comment]
Just an update, it is advised to use CMake generator expressions for macro stuff like this when fed into the add_custom_command directive:
https://cmake.org/cmake/help/v3.0/manual/cmake-generator-expressions.7.html#informational-expressions

I'm testing this approach now with some success with NMake JOM, but I haven't tested using the regular VS generators.

**Comment by boberfly** [comment]
https://github.com/appleseedhq/appleseed/pull/2060

**Comment by est77** [comment]
Done in #2060
