### ISSUE TITLE
Is BinaryMesh storing vertices and other vectors in double precision?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2066]

**Comment by rgirish28** [comment]
So, it appears BinaryMesh is storing vertices and Vectors in double precision. Checked_read reads data of the size of the datatype passed to it. It doesn't convert it down to a float if it is a double type passed to it.  In BinaryMesh, Vector3d and Vector2d are passed to checked_write. So, all values read and stored are in double precision.

**Comment by est77** [comment]
Yes, it would need a new version of the format. We want to keep reading the old files.

**Comment by dictoon** [comment]
As @est77 said, we need to maintain compabitility with existing files. I would recommend that you focus on your GSoC project for now; we'll take care of this at some later point, it's not urgent. Thanks for noticing the problem though, very much appreciated!

**Comment by dictoon** [comment]
Fixed in #2114.
