### ISSUE TITLE
File type ignored when saving an image

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2073]
Even if png is specified but the extension isn't written by the user, the image is exported as exr
![2018-06-01-10 35 23](https://user-images.githubusercontent.com/4656466/40830875-ca43aba6-6587-11e8-818b-8dfab88c6818.png)
![2018-06-01-10 35 37](https://user-images.githubusercontent.com/4656466/40830881-ce137eb4-6587-11e8-98ea-657048086feb.png)

**Comment by dictoon** [comment]
Definitely working for me.

**Comment by dictoon** [comment]
Only AOVs are always written as OpenEXR files.

**Comment by oktomus** [comment]
Yes I know, but here in the screenshots it's the final image. Even when having the same configuration as in the screenshots your image is being saved as png ?

**Comment by dictoon** [comment]
> Even when having the same configuration as in the screenshots your image is being saved as png

Yes, but I'm on Windows. You should ask someone on Linux.

**Comment by est77** [comment]
It seems the problem is here:
https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.studio/mainwindow/mainwindow.cpp#L1961

I am wondering how this code works on windows? It doesn't look like we use the selected filter to set the extension anywhere.

**Comment by dictoon** [comment]
It looks like by default it picks the first extension from the filter.

**Comment by dictoon** [comment]
> It doesn't look like we use the selected filter to set the extension anywhere.

We certainly don't need to do anything special on Windows. Can you investigate what's the expected behavior on Linux, and whether we need to do something special there?

**Comment by oktomus** [comment]
@est77 or myself ?

**Comment by dictoon** [comment]
Whoever has time :)

**Comment by oktomus** [comment]
It seems that the automatic extension is only working on windows.
https://stackoverflow.com/questions/7234381/specify-default-extension-in-qfiledialoggetsavefilename#15904546
It would be difficult to get the final selected filter to set the extension

**Comment by oktomus** [comment]
Actually, it won't be difficult, I can try :)
