### ISSUE TITLE
Build fails with glu 9.0.0-5

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2090]
With the new version of `glu` **9.0.0-5**, building fails 
```cpp
[ 73%] Linking CXX executable appleseed.studio                               
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/../../../../lib/libGLU.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'                                                                            
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/../../../../lib/libGLU.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'   
```
I had to downgrade `glu` to **9.0.0-4**

**Comment by dictoon** [comment]
Can we not fix something on our side to be compatible with glu 9.0.0-5? @est77?

**Comment by oktomus** [comment]
@dictoon yes we can compile it with the same compiler as Appleseed. Here it was my system `glu` so that's why it failed.

**Comment by dictoon** [comment]
I meant: can we do something in appleseed itself to make sure we can link with glu 9.0.0-5 without recompiling it?

**Comment by oktomus** [comment]
I don't think so. If any version of glu is not linked the same way as AS, there is no way you could use this glu for AS.

**Comment by dictoon** [comment]
I'm just surprised that glu exposes C++ symbols, I thought it was a pure C library.
