### ISSUE TITLE
After import of object file zooming and panning does not work anymore

### ISSUE THREAD

**Issue by daixtrose** [appleseedhq/appleseed#2092]
How to reproduce:

- Load the Cornell Box
- Remove all objects
- Load some object file

Ctrl+Middle Mouse or Ctrl+Right Mouse have no effect. Any hint what went wrong?

![image](https://user-images.githubusercontent.com/5588692/41512170-3ae87cd8-7285-11e8-8b87-2337d22f6a7a.png)

**Comment by dictoon** [comment]
Thanks for the report, that looks like a bug. We'll look into it.

**Comment by usakhelo** [comment]
Can't reproduce this, everything is working fine after the import.

**Comment by dictoon** [comment]
I cannt reproduce either, everything appears to work fine.
