### ISSUE TITLE
gcc-8.1 type conversion error.

### ISSUE THREAD

**Issue by bartoszek** [appleseedhq/appleseed#2093]
gcc(v8.1) complains about conversion form `foundation::AABBBase<double,3>` to `foundation::AABB<double,3>` in tree building here: https://github.com/appleseedhq/appleseed/blob/a7053a618c716ded4ae741030549c12ed80c46eb/src/appleseed/renderer/kernel/intersection/triangletree.cpp#L684
gcc error:
```
src/appleseed/foundation/math/bvh/bvh_sbvhpartitioner.h:321:32: error: conversion from ‘foundation::AABBBase<double, 3>’ to non-scalar type ‘foundation::bvh::SBVHPartitioner<renderer::TriangleItemHandler, std::vector<foundation::AABB<double, 3>, std::allocator<foundation::AABB<double, 3> > > >::AABBType’ {aka ‘foundation::AABB<double, 3>’} requested
             AABBType::intersect(object_split_left_bbox, object_split_right_bbox);
```

**Comment by dictoon** [comment]
Thanks for the report!

@oktomus Could you have a look please?
