### ISSUE TITLE
Emscripten compilation support?

### ISSUE THREAD

**Issue by kkimdev** [appleseedhq/appleseed#2150]
It would be really cool if appleseed supports Emscripten compilation.  Since appleseed is almost entirely c++ library, I think it might not be that difficult.

FYI: someone worked on cycles emscripten compilation few years ago: https://github.com/paulfitz/emcycles

**Comment by dictoon** [comment]
I agree that it would be awesome. However, although compiling appleseed itself with Emscripten shouldn't be too difficult, compiling all third party dependencies (including LLVM itself!) is a tall order.
