### ISSUE TITLE
Request: Add lens shift feature to cameras

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2153]
This is needed for some Blender features in interactive and stereoscopic rendering.

**Comment by jdent02** [comment]
This is needed for some Blender features in interactive and stereoscopic rendering.

**Comment by dictoon** [comment]
Duplicate of https://github.com/appleseedhq/appleseed/issues/569?

**Comment by jdent02** [comment]
Yeah. Whoops
