### ISSUE TITLE
Regression errors (Windows)

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2161]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	671	
Error	C2220	warning treated as error - no 'object' file generated	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	398	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	398	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	406	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	663	

Introduced with revision 1f97318139d754984aca3537292bd84c772d291c

**Comment by jdent02** [comment]
Other errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\..\appleseed.shared\Release\appleseed.shared.lib'	dumpmetadata	D:\appleseed\appleseed\build\src\tools\dumpmetadata\LINK	1	
Error	C2220	warning treated as error - no 'object' file generated	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	398	
Error	LNK1181	cannot open input file '..\appleseed\Release\appleseed.lib'	appleseed.shared	D:\appleseed\appleseed\build\src\appleseed.shared\LINK	1	
Error	LNK1181	cannot open input file '..\appleseed\Release\appleseed.lib'	appleseed.python	D:\appleseed\appleseed\build\src\appleseed.python\LINK	1	
Error	LNK1181	cannot open input file '..\appleseed\Release\appleseed.lib'	appleseed.python3	D:\appleseed\appleseed\build\src\appleseed.python\LINK	1	
Error	LNK1181	cannot open input file '..\appleseed.shared\Release\appleseed.shared.lib'	appleseed.cli	D:\appleseed\appleseed\build\src\appleseed.cli\LINK	1	
Error	LNK1181	cannot open input file '..\..\appleseed.shared\Release\appleseed.shared.lib'	convertmeshfile	D:\appleseed\appleseed\build\src\tools\convertmeshfile\LINK	1	
Error	LNK1181	cannot open input file '..\..\appleseed.shared\Release\appleseed.shared.lib'	animatecamera	D:\appleseed\appleseed\build\src\tools\animatecamera\LINK	1	
Error	LNK1181	cannot open input file '..\..\appleseed.shared\Release\appleseed.shared.lib'	makefluffy	D:\appleseed\appleseed\build\src\tools\makefluffy\LINK	1	
Error	LNK1181	cannot open input file '..\..\appleseed.shared\Release\appleseed.shared.lib'	projecttool	D:\appleseed\appleseed\build\src\tools\projecttool\LINK	1	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	398	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	406	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	663	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	appleseed	D:\appleseed\appleseed\src\appleseed\renderer\kernel\rendering\final\adaptivetilerenderer.cpp	671

**Comment by dictoon** [comment]
The latter linking errors are caused by the former minor compilation errors (warnings really, but warnings are considered as errors in appleseed). They are simple to fix.
