### ISSUE TITLE
Allow interpreting normals either as DirectX or OpenGL

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2205]
From @Dark_z on Discord:

> Can you add a way to switch normal interpretation as either DirectX or OpenGL? My normal map which I exported from Substance is set to OpenGL but ends up flipped in Appleseed, as if Appleseed is using the DirectX style.

**Comment by est77** [comment]
This is available in the new as_bump shader. The old gaffer shaders are deprecated and will be removed soon.
