### ISSUE TITLE
Add built-in support dithering when saving 8-bit images

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2235]
Requested on the forum: https://forum.appleseedhq.net/t/color-banding/603/4

**Comment by juancarlosgzrz** [comment]
Is this related? https://github.com/OpenImageIO/oiio/blob/master/testsuite/dither/run.py

**Comment by juancarlosgzrz** [comment]
![image](https://user-images.githubusercontent.com/26150363/48429546-4a85ff00-e722-11e8-8986-bbee77284449.png)

**Comment by dictoon** [comment]
It's related in the sense that yes, OIIO supports dithering natively and I have a changeset that exposes this to appleseed. Just need to prepare it and submit a PR.

**Comment by dictoon** [comment]
Done.
