### ISSUE TITLE
OpenGL render in Light Paths tab is glitchy on macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2239]
On a MacBook Pro, it either shows the content beneath appleseed.studio's window, or it's black:

![image](https://user-images.githubusercontent.com/321290/47048882-fd9f1f00-d19b-11e8-9849-8653098e20ab.png)

On a macOS VM, it flickers between black and the correct render.

**Important: it used to work fine with appleseed 1.9.0-beta.**

**Comment by pjessesco** [comment]
I couldn't install macOS 10.10 on my mac, I need some time to solve it :(

**Comment by dictoon** [comment]
No worry.

I don't think you want to install macOS 10.10 on your Mac, why would you want to do that?

**Comment by pjessesco** [comment]
I found 2.0.0 beta package that you uploaded on dropbox is build with clang 10.0(macOS 10.14). So I just want to check if master branch's code works well when it built with clang 7.0 (that is, on macOS 10.10) like 1.9 release package one.

**Comment by pjessesco** [comment]
Update : I build with clang 7.0.2, OpenGL renderer seems work well.

![screen shot 2018-11-02 at 12 27 20 am](https://user-images.githubusercontent.com/11532321/47861994-71e1ef80-de37-11e8-91cc-d720993064e7.png)

**Comment by dictoon** [comment]
Oh that's interesting! Are you sure it's related to clang's version? Isn't it more about macOS's version?

**Comment by pjessesco** [comment]
I'm not sure because I have no idea if I can install different version of clang.

**Comment by pjessesco** [comment]
I installed clang 7 on macOS 10.14, it still doesn't work. 
<img width="835" alt="2018-11-07 12 20 00" src="https://user-images.githubusercontent.com/11532321/48323844-7f864900-e671-11e8-8d8b-71dc1682aed4.png">

White area is not blank, it actually filled with white color. I couldn't install clang 10 on macOS 10.10. I guess it is about macOS version as you said..

**Comment by dictoon** [comment]
Thanks for checking! Yes I think it's logical that it's related to the macOS version and not the compiler. It would be interesting to dig deeper. Also, we have deprecation warnings on OpenGL calls when building on macOS 10.14 (with the clang version provided with the developer tools), we need to shut those off for now.

**Comment by pjessesco** [comment]
> we need to shut those off for now.

Yes. I can fix it, and this issue is only for macOS 10.14.

**Comment by pjessesco** [comment]
Wow, have no idea how I debug it :(

**Comment by dictoon** [comment]
Maybe start by commenting the whole OpenGL code? Or keep just the buffer clearing?

**Comment by pjessesco** [comment]
It seems solved since @termhn upgrade to Qt5, I can't reproduce bug [I mentioned](https://github.com/appleseedhq/appleseed/pull/2509#issuecomment-477874073).


<img width="949" alt="스크린샷 2019-04-09 오후 4 08 40" src="https://user-images.githubusercontent.com/11532321/55779936-c0c83b00-5ae1-11e9-905b-38776404d1fc.png">

**Comment by dictoon** [comment]
Good to hear, thanks for testing! I'll close this ticket then, we can open a new one (or reopen this one) if needs be.
