### ISSUE TITLE
Print more runtime details in Python utilities

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2284]
Print:
- Date/Time
- Python version
- Path to script
- Script version

**Comment by MahidharBandaru** [comment]
Hi! I would like to take up this issue. By saying Python utilities are you referring to the scripts in this directory?
[scripts](https://github.com/appleseedhq/appleseed/tree/master/scripts)

**Comment by jsxs0** [comment]
I believe, **date/time** can be added by 
`import datetime
now = datetime.datetime.now()
print
print "Date/time:"
print str(now)
print
print "Current date and time:"
print "Current year: %d" % now.year
print "Current month: %d" % now.month
print "Current day: %d" % now.day
print "Current hour: %d" % now.hour
print "Current minute: %d" % now.minute
print "Current second: %d" % now.second
print "Current microsecond: %d" % now.microsecond
print
print "Current date and time using strftime:"
print now.strftime("%Y-%m-%d %H:%M")
print
print "Current date and time using isoformat:"
print now.isoformat()
`
If this piece of code is added in the code debugger, we can probably see the date/time
**Python version**
```
import sys
print sys.version #from Script
```
**Path to script**
`os.path.realpath(__file__)`
OR, I could also use
`import os
print os.__file__`
**Script version**
```
import platform;

print(platform.sys.version);
```
Or, a simpler version could be:
`import sys
print sys.version`

**Comment by dictoon** [comment]
@jsxs0 Please don't post tutorials about basic Python functions, these information are available in abundance on the web.

**Comment by dictoon** [comment]
@MahidharBandaru Yes. Two scripts that would benefit from these information are `appleseed.package.py` and `runtestsuite.py` (both in the console and the HTML report).

**Comment by tyxchen** [comment]
I can work on this issue.

Out of curiosity, what is meant by "script version"? Would the Git hash of the commit where the script was last changed suffice?
