### ISSUE TITLE
Linux build guide should mention "WARNINGS_AS_ERRORS"

### ISSUE THREAD

**Issue by leoschwarz** [appleseedhq/appleseed#2316]
Hi

I've just had a while to compile appleseed on Linux (Debian 9 with gcc 6.3.0-18+deb9u1) because I've got the following warning and took a moment to figure out how to remove `-Werror` until I've found a different issue here mentioning the solution:

```
In file included from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/shading/shadingpoint.h:50:0,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/curvetree.h:37,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/intersector.h:34,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:33:
~/appleseed-2.0.0-beta/src/appleseed/foundation/math/basis.h: In member function ‘virtual bool renderer::{anonymous}::RandomwalkBSSRDF::sample(const renderer::ShadingContext&, renderer::SamplingContext&, const void*, const renderer::ShadingPoint&, const Vector3f&, renderer::BSSRDFSample&, renderer::BSDFSample&) const’:
~/appleseed-2.0.0-beta/src/appleseed/foundation/math/basis.h:197:24: warning: ‘slab_normal’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     const T b = m_n[0] * m_n[1] * a;
                 ~~~~~~~^~~~~~
~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:302:22: note: ‘slab_normal’ was declared here
             Vector3f slab_normal;
                      ^~~~~~~~~~~
In file included from /appleseed-2.0.0-beta/src/appleseed/renderer/kernel/shading/shadingpoint.h:50:0,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/curvetree.h:37,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/intersector.h:34,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:33:
~/appleseed-2.0.0-beta/src/appleseed/foundation/math/basis.h:197:24: warning: ‘*((void*)& slab_normal +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     const T b = m_n[0] * m_n[1] * a;
                 ~~~~~~~^~~~~~
~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:302:22: note: ‘*((void*)& slab_normal +4)’ was declared here
             Vector3f slab_normal;
                      ^~~~~~~~~~~
In file included from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/shading/shadingpoint.h:50:0,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/curvetree.h:37,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/kernel/intersection/intersector.h:34,
                 from ~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:33:
~/appleseed-2.0.0-beta/src/appleseed/foundation/math/basis.h:196:33: warning: ‘*((void*)& slab_normal +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     const T a = T(-1.0) / (sign + m_n[2]);
                           ~~~~~~^~~~~~~~~
~/appleseed-2.0.0-beta/src/appleseed/renderer/modeling/bssrdf/randomwalkbssrdf.cpp:302:22: note: ‘*((void*)& slab_normal +8)’ was declared here
             Vector3f slab_normal;
                      ^~~~~~~~~~~
```

Maybe this is warning is even fixed in latest master branch, but anyhow I had to use `-DWARNINGS_AS_ERRORS=OFF` to build appleseed successfully, maybe since other people with other compilers might run into it would be best to add a note to https://github.com/appleseedhq/appleseed/wiki/Building-appleseed-on-Linux , I'd simply add after "While this will usually work, we do not officially support this scenario." "You might have to additionally pass the `-DWARNINGS_AS_ERRORS=OFF` flag to prevent compiler specific warnings breaking your build." (I didn't want to edit the wiki directly since I know anything about your project policies.)

**Comment by dictoon** [comment]
Glad that you found out about `-DWARNINGS_AS_ERRORS=OFF`. We didn't document it because warnings-as-errors aren't supposed to be enabled for builds in the `Ship` configuration (except on Windows but this is already a known issue: https://github.com/appleseedhq/appleseed/issues/2272 and there's already a proposed fix: https://github.com/appleseedhq/appleseed/pull/2274) which is the configuration recommended by the build instructions.

If you're building in `Debug` or `Release` configurations, then warnings-as-errors is enabled, on purpose. We probably should document `-DWARNINGS_AS_ERRORS=OFF` but the best approach is for developers that encounter new warnings to propose fixes. We welcome pull requests :)

**Comment by dictoon** [comment]
I just realized that our Linux build instructions recommend building the `Release` configuration. That's a bug, I'll fix it now.

**Comment by dictoon** [comment]
Just added a section about warnings to the Linux build instructions:
https://github.com/appleseedhq/appleseed/wiki/Building-appleseed-on-Linux

Review and comments appreciated!

**Comment by leoschwarz** [comment]
Hi. I think it's great, thanks for your efforts! I think it would help other people in the future with the same issue. Only might maybe want to add that Ship is the default build type but honestly this is a detail and easy to see using ccmake or on reading the top level cmake file, otherwise I think this issue is solved.

**Comment by dictoon** [comment]
Thanks for the feedback! Good point on `Ship` being the default build type, I'll mention it.

**Comment by dictoon** [comment]
Done.
