### ISSUE TITLE
Allow driving image space sampling with a B&W texture

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2354]
In the black and white texture, black pixels would mean 0 sample for the corresponding pixel in the final render, 255 would mean full sampling rate for the corresponding pixel, and intermediate value would allow controlling the sampling rate.

This is probably best implemented in a separate pixel renderer. `MapPixelRenderer`? Think of a better name.

**Comment by BashPrince** [comment]
I'll start work on this.

**Comment by dictoon** [comment]
Done.
