### ISSUE TITLE
Add documention for as_texture node

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2361]

**Comment by luisbarrancos** [comment]
I just noticed the as_texture node was in category "procedural texture nodes". That entire section should be "texture nodes" only.

**Comment by dictoon** [comment]
I see. I agree, the section title is misleading.

Are information about UDIM tiles up-to-date and accurate in the `as_texture` node documentation?

**Comment by dictoon** [comment]
Also fix typos and improve clarity of comment block in as_texture.osl:
https://github.com/appleseedhq/appleseed/blob/1b6d2074efed700ccc32da5e2af0ed6dc030ec34/src/appleseed.shaders/src/appleseed/as_texture.osl#L332-L351

**Comment by dictoon** [comment]
Done.
