### ISSUE TITLE
Review albedo initialization in BSDFs

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2372]
It seems that some BSDFs don't return the correct albedo, for instance the Diffuse BTDF (`diffusebtdf.cpp`) returns `values->m_transmittance` while it should probably return `sample.m_value.m_diffuse`:

    // Compute the BRDF value.
    sample.m_value.m_diffuse = values->m_transmittance;
    sample.m_value.m_diffuse *= values->m_transmittance_multiplier * RcpPi<float>();
    sample.m_value.m_beauty = sample.m_value.m_diffuse;

    // ...

    sample.m_aov_components.m_albedo = values->m_transmittance;

Same problem with the Diffuse BRDF, and possibly others.

**Comment by mandeep** [comment]
@dictoon I'm going to take a look at this and will let you know if I have any questions.

**Comment by mandeep** [comment]
So it looks like in `diffusebtdf.cpp` m_albedo needs to be set to m_diffuse. Then we need to call sample.compute_transmitted_differentials(eta) correct?
