### ISSUE TITLE
Do not use immediate mode OpenGL in BlenderProgressiveTileCallback

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#2373]

**Comment by Narann** [comment]
Reading the code, the immediate mode is only used in [draw_pixels](https://github.com/appleseedhq/appleseed/blob/3e225130ece5dc95a0ff7108c944aa396abce47a/src/appleseed.python/bindblenderprogressivetilecallback.cpp#L149) to draw a rectangle on screen.

It shouldn't be too hard to replace by preparing a simple shader and just allocating a vertex buffer and an index buffer. Everything to do the job should be is [here](https://open.gl/drawing). [Another example](https://www.haroldserrano.com/blog/loading-vertex-normal-and-uv-data-onto-opengl-buffers) for UV. And last, [more in depth](https://learnopengl.com/Getting-started/Textures) for textures.

In modern OpenGL you:

* Allocate buffers (shader, position/uv, textures) at startup and feed them with what will never change (shader, uv).
* Bind buffers to modify them (position, texture data) and draw.

**Comment by dictoon** [comment]
@Narann Could you have a look at @anikket786's PR? https://github.com/appleseedhq/appleseed/pull/2388/files

**Comment by termhn** [comment]
Hi @anikket786 are you still working on your PR? If not I think I'm going to take a look at this issue...

**Comment by dictoon** [comment]
Go ahead @termhn.

**Comment by mororo250** [comment]
Hi @termhn are you working on this issue?

**Comment by termhn** [comment]
@mororo250 I am not anymore, no. You can give it a shot, but it is non-obvious what the correct solution here is; someone that is more familiar with how blender internals work would be helpful

**Comment by mororo250** [comment]
thanks, I will give it a try!
