### ISSUE TITLE
Optimize light paths visualization (OpenGL)

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2393]
We're currently using old-school immediate mode OpenGL to visualize light paths (and the scene). Move toward a more modern (VBO-based?) approach.

The relevant code is in `src/appleseed.studio/mainwindow/rendering/lightpathswidget.cpp`.

**Comment by termhn** [comment]
Going to be taking a look at this in the next few days hopefully

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
