### ISSUE TITLE
Update OSL shaders with holdout matte calls

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2397]
Related: https://github.com/appleseedhq/appleseed/pull/2232

**Comment by luisbarrancos** [comment]
This was superceded by https://github.com/appleseedhq/appleseed/pull/2374
We have far better control with our *as_matte* call.
The generic appleseed shaders were updated with that same PR. The remaining ones (Maya), are going to be addressed in https://github.com/appleseedhq/appleseed-maya/issues/192
