### ISSUE TITLE
appleseed.studio doesn't launch after python folder name change merge

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2398]
Hey Franz, looks like your recent PR to change the name of the Python27 folder ran into the same issue I was having: appleseed.studio will no longer launch from a package install.

Steps to reproduce: Build recent master branch, run packaging script, try to launch .studio from resulting package, nothing happens.

**Comment by Mango-3** [comment]
I confirm this, had the same issue. I fixed it on my system by setting a PYTHONHOME environment variable pointing to a Python 2.7 installation. Then appleseed.studio starts again.
