### ISSUE TITLE
`shutter_curve_control_points` is marked as optional but uses `get_required()`

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#2417]
Not a bug, I'm just tracking it.

https://github.com/appleseedhq/appleseed/blob/c5c3ef90c090bb17a5677072185d8cab040a54c4/src/appleseed/renderer/modeling/camera/camera.cpp#L744

https://github.com/appleseedhq/appleseed/blob/c5c3ef90c090bb17a5677072185d8cab040a54c4/src/appleseed/renderer/modeling/camera/camera.cpp#L374

**Comment by dictoon** [comment]
As intended:

    m_params.get_required<Impl::ShutterCurveCP>("shutter_curve_control_points")

is only called when

    impl->m_use_bezier_shutter_curve

is true, and this is only true when the `shutter_curve_control_points` parameter actually exists.

**Comment by Narann** [comment]
My bad, thanks.
