### ISSUE TITLE
Add "Object ID" override shading

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#2420]
For now, there is only "Object Instances". But to check which objects are instanciated we need an "Object ID" override shading:

![image](https://user-images.githubusercontent.com/659708/52599357-b3336380-2e58-11e9-8d85-67ee350f4523.png)

This override would return the ID color of the object (not the object instance) used by the shape.

**Comment by dictoon** [comment]
Makes a lot of sense. To be consistent with the other names, I suggest to:

- Call it simply "Objects"
- Add "Assemblies"

So we would end up with:

- Assemblies
- Assembly Instances
- Objects
- Object Instances

in that order.

**Comment by Himanshu-Garg** [comment]
is anyone working on this ?

**Comment by dictoon** [comment]
Nope, good ahead!

**Comment by jsxs0** [comment]
Is this issue available, to work upon?

**Comment by Himanshu-Garg** [comment]
Yes, not working on it rightnow

**Comment by jsxs0** [comment]
> 
> 
> Yes, not working on it rightnow

Okay, thanks. Will work on it

**Comment by bassemhermina** [comment]
So, I've been fiddling around with this issue as my entrance for Appleseed, and somehow I figured out how to solve it, so is anybody still working on it, or can I submit my fix?

**Comment by jsxs0** [comment]
Yes, even I was finding my way to work about it but eventually found another issue to work on. You can go ahead, goodluck!

**Comment by bassemhermina** [comment]
Thank you! Then I’ll have it.

**Comment by dictoon** [comment]
Done.
