### ISSUE TITLE
Remove adaptive pixel sampler

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#2448]
Now that we have an adaptive tile sampler, there is very little reason to use or maintain the adaptive pixel sampler.

**Comment by dictoon** [comment]
Indeed. Make sure to include a project migration step to either the Adaptive Tile Renderer if that sounds feasible, or more like to the Uniform Pixel Renderer, _with a warning message that the project conversion had to make this simplification_.

**Comment by dictoon** [comment]
Done.
