### ISSUE TITLE
Albedo AOV is wrong with Ashikhmin-Shirley BRDF

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2450]
Repro case (Cornell Box with Albedo AOV): [cb-albedo-aov.zip](https://github.com/appleseedhq/appleseed/files/2922988/cb-albedo-aov.zip)

Albedo AOV:

![cb-albedo-aov](https://user-images.githubusercontent.com/321290/53693768-1a33a080-3da5-11e9-856b-98c34ccd6b40.png)

We shouldn't see glossy reflections.

**Comment by wilimitis** [comment]
I believe I've traced the issue down to this [mechanism](https://github.com/appleseedhq/appleseed/pull/2040/commits/ec8faae29bace9f404dbbe928fcf40bd2a20da2d#diff-83a1e04b0c52a327a4324eb22cfdec16R717) which causes accumulation of albedo AOVs on `*D` paths as opposed to `D`, thus `G+D` paths can be sampled, resulting in glossy reflections.

If this is a bug, it seems pervasive in at least any BXDF which can be sampled as both glossy and diffuse. For instance, the albedo AOV from the `Metal` brdf.

![Screen Shot 2019-03-11 at 6 08 15 AM](https://user-images.githubusercontent.com/4917232/54119757-17980300-43c4-11e9-8666-98db7800905f.png)

After a correction to only mark `D` paths

| Ashikhmin-Shirley | Metal |
| --- | --- |
| ![Screen Shot 2019-03-11 at 6 13 18 AM](https://user-images.githubusercontent.com/4917232/54120074-cdfbe800-43c4-11e9-8ace-35ad65e74728.png) | ![Screen Shot 2019-03-11 at 6 13 21 AM](https://user-images.githubusercontent.com/4917232/54120083-d2c09c00-43c4-11e9-857b-08b6966d096c.png) |

If this is what we want (as opposed to, say, considering indirect diffuse as well) then I'll PR my branch.

(I know this isn't marked as `Good First Issue`, but I figured looking into this would be a good exercise in familiarizing myself with appleseed's light transport data structures 🤷‍♂️.)

**Comment by dictoon** [comment]
> (I know this isn't marked as Good First Issue, but I figured looking into this would be a good exercise in familiarizing myself with appleseed's light transport data structures 🤷‍♂️.)

By all means, feel free to explore and tackle any issue, even those not marked as Good First Issue :) We use this tag to highlight good starting points for new contributors, but the intent is certainly not to limit the choice to those tasks :)

**Comment by dictoon** [comment]
> it seems like the original PR was aiming to implement diffuse_albedo

Absolutely.

The results you're getting definitely look more correct. It's indeed likely that this bug exists in most (or all) G+D BSDFs.

Feel free to open a PR, even just a draft one.

Thanks!

**Comment by est77** [comment]
The output of the AOV should be the albedo of the first diffuse scattering event we found along a path.
The results of the first metal render are correct.

**Comment by wilimitis** [comment]
> albedo of the first diffuse scattering event we found along a path

I'm probably missing something, but this makes me think the feature overall is working as expected then, and that the Ashikhmin-Shirley render @dictoon posted is in fact correct.

The following discussion seems to support this notion: https://discordapp.com/channels/430063582777049089/430064067873472526/464550763977506827.

**Comment by est77** [comment]
I think that the issue is in asSbsPbrMaterial, not in the way we compute the albedo, which matches what other renderers do.

Correct (asStandardSurface shader):
![standard_surface_albedo](https://user-images.githubusercontent.com/409013/54153074-f4f70000-443e-11e9-91f5-234783beed05.png)

Incorrect (asSbsPbrSurface):
![sbspbr_surface_albedo](https://user-images.githubusercontent.com/409013/54153107-0e984780-443f-11e9-9a13-fd138db295c5.png)

**Comment by dictoon** [comment]
Ok, then I stand corrected. @est77 Should we close this issue then?

Regarding the black albedo, there's another ticket about `asStandardSurface`: https://github.com/appleseedhq/appleseed/issues/2450. At least that's how it had been reported, maybe the original reporter meant `asSbsPbrSurface`.

**Comment by dictoon** [comment]
It's best to close issues when they actually have been fixed, and to reference the PR that fixed it. That way, if the PR is closed, forgotten, abandonned, etc. then the open issue is still there to remind us that it needs fixing.

**Comment by est77** [comment]
There is no issue here. The bug I showed in the screenshots is in an unrelated part of the code.

**Comment by dictoon** [comment]
My bad 😂

**Comment by dictoon** [comment]
For reference, the two related issues: #2372, #2436.
