### ISSUE TITLE
libSM and libuuid error when building

### ISSUE THREAD

**Issue by kushWithoutWax** [appleseedhq/appleseed#2452]
Using gcc 4.8.5 on Ubuntu 16.04.5, I faced some issues while building appleseed studio.

 Linking CXX executable appleseed.studio
```bash
**//usr/lib/x86_64-linux-gnu/libSM.so.6: undefined reference to `uuid_generate@UUID_1.0'
//usr/lib/x86_64-linux-gnu/libSM.so.6: undefined reference to `uuid_unparse_lower@UUID_1.0'**
collect2: error: ld returned 1 exit status
src/appleseed.studio/CMakeFiles/appleseed.studio.dir/build.make:8119: recipe for target 'src/appleseed.studio/appleseed.studio' failed
make[2]: *** [src/appleseed.studio/appleseed.studio] Error 1
CMakeFiles/Makefile2:527: recipe for target 'src/appleseed.studio/CMakeFiles/appleseed.studio.dir/all' failed
make[1]: *** [src/appleseed.studio/CMakeFiles/appleseed.studio.dir/all] Error 2
```

I used the prebuilt dependencies package and used cmake with the flags in https://github.com/appleseedhq/appleseed/wiki/Building-appleseed-on-Linux

**Comment by est77** [comment]
This is caused most likely because of using precompiled libs built on Fedora on Ubuntu.
The correct fix is to add -DAPPLESEED_LINK_EXTRA_LIBRARIES=-luuid to the cmake command line 
(or rebuild the dependencies on Ubuntu).
