### ISSUE TITLE
Add OpenImageIO's idiff tool to appleseed distribution

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2480]
Prerequisite of #2481.

**Comment by slongle** [comment]
If nobody work on it, I'd like to do it.

**Comment by dictoon** [comment]
Go ahead.

**Comment by slongle** [comment]
I'm not sure about my thought about it now.
I just want to add the idiff.exe into appleseed\scripts\tools with the new folder named idiff.
The structure is
appleseed
| -- scripts
|       | -- tools
|       |        | -- cloc
|       |        |        `--cloc.exe
|       |        | -- idiff
|       |        |        `--idiff.exe
.....
I think then it can be used by the **.py
Is this what you want?

**Comment by est77** [comment]
We already bundle a tool called oiiotool from OpenImageIO. Just copy what we do for oiiotool.

**Comment by slongle** [comment]
Thanks est, I get it.

**Comment by slongle** [comment]
For the linux, there isn't an idiff in prebuilt-linux-deps.
So, can I update that?

**Comment by est77** [comment]
I added it to the deps.
