### ISSUE TITLE
Recent changes cause build failure in 'Release' mode

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2490]
Recent changes involving the post processing stage is causing a build failure in 'Release' mode due to 'Warnings as errors" being active.

1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\simd.h(3824): warning C4244: '=': conversion from 'float' to 'int', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)
1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\simd.h(3833): warning C4244: '=': conversion from 'float' to 'int', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)
1>projectfileupdater.cpp
1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\fmath.h(1131): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)
1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\fmath.h(1157): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)
1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\fmath.h(1180): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)
1>d:\appleseed\appleseed-deps_boost166\stage\vc141\oiio-debug\include\openimageio\fmath.h(1214): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data (compiling source file D:\appleseed\appleseed_py35\src\appleseed\renderer\modeling\postprocessingstage\renderstamppostprocessingstage.cpp)

Appears to be OIIO related.  Disabling "Warnings as Errors" allowed build to complete.

**Comment by dictoon** [comment]
Fixed in #2484.
