### ISSUE TITLE
Rename tests related build options

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2513]
The only available flag right now is `WITH_TESTS` and it only determines whether unit tests and benchmarks are installed, not whether they are compiled.

- [ ] Rename `WITH_TESTS` to something more appropriate according to what it actually does like `INSTALL_TESTS`

**Comment by pjessesco** [comment]
Isn't it done?

**Comment by dictoon** [comment]
It is done, good catch!
