### ISSUE TITLE
Fullscreen checkbox not shown when in full screen

### ISSUE THREAD

**Issue by mandeep** [appleseedhq/appleseed#2519]
In appleseed.studio when entering Fullscreen via View->Fullscreen, there is no indication (besides the layout changing) that the user is in full screen mode. In Fullscreen when the user clicks on View->Fullscreen, there isn't a checkbox next to Fullscreen indicating that the user is in this mode.

**Comment by dictoon** [comment]
That's a good idea.

**Comment by amanbora** [comment]
Hi, I would like to work on this issue

**Comment by oktomus** [comment]
@amanbora, @mandeep  has already submitted a pull request for this.
