### ISSUE TITLE
Fix styling regressions after switch to Qt 5

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2536]
See https://github.com/appleseedhq/appleseed/pull/2509#issuecomment-480867141 for details.

**Comment by pjessesco** [comment]
<img width="400" alt="스크린샷 2019-04-09 오후 4 15 25" src="https://user-images.githubusercontent.com/11532321/55780372-bc505200-5ae2-11e9-8daa-41479c8f5a46.png">

**Comment by dictoon** [comment]
Fixed in #2595.
