### ISSUE TITLE
Remove Qt 'QCocoaView handleTabletEvent' warnings on OS X

### ISSUE THREAD

**Issue by jonathantopf** [appleseedhq/appleseed#254]
Currently when using a Wacom tablet on OS X you get this warning multiple times in the console as appleseed.studio runs:

QCocoaView handleTabletEvent: This tablet device is unknown (received no proximity event for it). Discarding event.

It's not a problem just a minor irritation.

**Comment by dictoon** [comment]
Still an issue on OS X 10.10 Yosemite inside VMware Player 7.1.2, with Qt 4.8.7.

**Comment by dictoon** [comment]
Fixed.
