### ISSUE TITLE
Update appleseed.package script after update to Qt 5

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2540]
Currently looks for Qt4.dll

**Comment by przemb** [comment]
Hi, 
I would like to start my open source journey from this issue. ;)

**Comment by jdent02** [comment]
Go ahead. It’s a straightforward fix

**Comment by przemb** [comment]
@jdent02 just to make sure... is this complete switch from Qt4 to Qt5? 
or rather extension? should I extend script or rather replace all occurrences of qt4?

**Comment by jdent02** [comment]
It’s a complete change

**Comment by przemb** [comment]
Due to problems with building project, which I described on Discord, I am temporarily blocked.
Feel free to take this issue.

**Comment by dictoon** [comment]
Fixed in #2595.

**Comment by pjessesco** [comment]
Is it done for macOS too?

**Comment by dictoon** [comment]
It isn't but it shouldn't be too complicated, hopefully. Feel free to have a go at it if you feel like!
