### ISSUE TITLE
Allow building Python 3 bindings without having to build Python 2 bindings

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2575]

**Comment by Mango-3** [comment]
Just wondering, the Python 2 bindings are probably needed in studio to access the appleseed Python functions via console. So when one builds studio, the Python 2 bindings are necessary, unless studio switches to use Python 3 internally.

**Comment by jdent02** [comment]
That is true.  I've actually implemented this fix (but I haven't PR'ed yet).  If you enable .studio it does check to make sure the USE_PYTHON2_BINDINGS is active as well.  It flashes an error if not.

The goal is mainly for blenderseed.  I don't need .studio, the tools, or the Python 2 bindings for that so it's a waste of compile time when they're active.  .studio and the tools could be disabled but not the Python 2 bindings.

**Comment by jdent02** [comment]
#2588
