### ISSUE TITLE
Checkpoints don't resume if passes aren't specified as a command line argument

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2597]
I have set 50 passes in my `appleseed` file 
```
<parameter name="passes" value="50" />
```
and only rendered `2`. And yet the checkpoint systems think the render is done.
```
 warning | the requested passes have already been rendered and saved into the checkpoint.
```

Although, if I specify the passes in the command line (i.e. `--passes 50`), the checkpoint system resume the render correctly.

**How to reproduce**

- Take an `appleseed` file and set a high number of passes in the `final` configuration. 
- Render few passes of this project and create a checkpoint
```    
appleseed.cli.exe  --message-verbosity debug  --checkpoint-create --output output.exr scene.appleseed
````
- Try to resume the render -> **fails**
```
appleseed.cli.exe  --message-verbosity debug  --checkpoint-create --checkpoint-resume --output output.exr scene.appleseed
```
- Try to resume the render with CL passes argument -> **success**
```
appleseed.cli.exe  --message-verbosity debug  --checkpoint-create --checkpoint-resume --passes 50 --output output.exr scene.appleseed
```

**Comment by LZaw** [comment]
I reproduced the issue on a Linux machine (using the Cornell Box), showing the exact same behaviour as described above.

**Comment by dictoon** [comment]
I'm on it.

**Comment by dictoon** [comment]
Fixed.
