### ISSUE TITLE
New rectangle_object size/position errors

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2612]
Got a good one for you.

Recently I switched the area lamps in Blender over to the new analytic shapes.  Spheres and discs work as expected, but there are some issues with the rectangles.

Here is an array of disc lights with a 0.5 radius:
![disc_0 5](https://user-images.githubusercontent.com/13521172/57953264-37144600-78b5-11e9-8e40-ca0b57f652a6.jpg)

Here's the same with 0.25:
![disc_0 25](https://user-images.githubusercontent.com/13521172/57953276-3e3b5400-78b5-11e9-847d-bc1ba976b769.jpg)

As you can see, the size changes correctly and the objects remain in place.

Here's rectangles at 1x1:
![1x1](https://user-images.githubusercontent.com/13521172/57953305-51e6ba80-78b5-11e9-9e89-1728652cff13.jpg)

Here's the same thing at 1x2:
![1x2](https://user-images.githubusercontent.com/13521172/57953317-590dc880-78b5-11e9-9920-edc4e5f66376.jpg)

As you can see, the shapes themselves have shifted from the proper locations and shrunk in size.  The matrices of each object were not changed, only the width parameter on the object entity.

Here's 1x3:
![1x3](https://user-images.githubusercontent.com/13521172/57953369-7e023b80-78b5-11e9-9352-6ed79f4a6f1d.jpg)

It get's even worse there.

Here's the scene files:
[as_test_file.zip](https://github.com/appleseedhq/appleseed/files/3192948/as_test_file.zip)

**Comment by usakhelo** [comment]
Hi @jdent02,
You have visible rectangle lights in Blender! I couldn't make them visible in max plugin. Interesting. I'll check your code.

**Comment by jdent02** [comment]
They’re the same as a mesh so if they’re visible to camera rays they should show up (unless you’re looking at the backside)

**Comment by usakhelo** [comment]
In one of my tests I actually see the rectangle, it's just very small. Maybe I have the same problem in max with incorrect rectangle scale or transforms...
On this image it should be the same size, but it's tiny:
![image](https://user-images.githubusercontent.com/1850877/57997357-2d980300-7a9a-11e9-8dfb-d487740f82e9.png)
