### ISSUE TITLE
Error message during rendering of any material in max or studio

### ISSUE THREAD

**Issue by usakhelo** [appleseedhq/appleseed#2622]
Hi,
I'm not 100% sure but I think it's not just max plugin error. I rendered scene in studio and got the same error message:

`while preparing bsdf "/glass_bsdf" for rendering a frame: required parameter "volume_parameterization" not found; continuing using value "transmittance".
`
Attached is the test scene:
[test_glass_warning.zip](https://github.com/appleseedhq/appleseed/files/3196242/test_glass_warning.zip)

**Comment by dictoon** [comment]
I think it _is_ a max error, `volume_parameterization` is a required parameter of the Glass BSDF so it must be set:

    metadata.push_back(
        Dictionary()
            .insert("name", "volume_parameterization")
            .insert("label", "Volume Absorption Parameterization")
            .insert("type", "enumeration")
            .insert("items",
                Dictionary()
                    .insert("Transmittance", "transmittance")
                    .insert("Absorption", "absorption"))
            .insert("use", "required")
            .insert("default", "transmittance")
            .insert("on_change", "rebuild_form"));

**Comment by est77** [comment]
It should happen with OSL too. We don't set it when creating the Glass BSDF inside the OSLBSDF.

**Comment by dictoon** [comment]
Indeed. Proposed fix: https://github.com/appleseedhq/appleseed/pull/2623. Please review.

**Comment by dictoon** [comment]
Fixed.
