### ISSUE TITLE
Override parameter depending on the ray type (ray switch system)

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#264]
As AS is a full raytracer renderer, a ray switch system could be a good point.

Most renderer provide a way to override a shading parameter depending on the ray type:
- camera
- GI
- reflection
- refraction
- secondary (GI+reflection+refraction)
- bounce number (to make the ray switch enabled only on after specific bounce number )

This way you can, for example, disable reflection in GI rays and avoid possible unnecessary ray (at and decrease render times).

**Comment by juancarlosgzrz** [comment]
I think this is already done

**Comment by dictoon** [comment]
You're right, this is fully supported in OSL.
