### ISSUE TITLE
Sampling issues with area light rendering

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2640]
Having some bad errors when using a triangle or analytic rectangle as an area light.

The sampling of the light appears to be quite poor, getting this results after 64 samples:

![unknown](https://user-images.githubusercontent.com/13521172/59275609-42dbf980-8c22-11e9-9ba5-210d6aa0dd8b.png)

Going into progressive rendering mode appears to give the same results.  However, if the progressive render state is updated (using AbortRendering and ContinueRendering controls) the quality exponentially increases when the render resumes.  Here's a video showing the effect:

https://cdn.discordapp.com/attachments/430064067873472526/587977584646684682/2019-06-11_07-10-34.mp4

This is through the Blender plugin.  I haven't had a chance to check if it does the same thing in appleseed.studio yet.

**Comment by jdent02** [comment]
[hall_test.zip](https://github.com/appleseedhq/appleseed/files/3279364/hall_test.zip)

**Comment by oktomus** [comment]
Indeed this is a serious bug, thanks!
