### ISSUE TITLE
Parameters for test scene for random-walk SSS

### ISSUE THREAD

**Issue by xelatihy** [appleseedhq/appleseed#2650]
Is the test scene for random walk SSS used in the 2.0 release available for testing? 
Te be clear, the scene for the image below

https://user-images.githubusercontent.com/321290/47671428-c7a46680-dbaf-11e8-97b2-79afeb54992d.png

**Comment by Mango-3** [comment]
Hi @xelatihy,
You have to ask @juancarlosgzrz about the scene and the material parameter. He is the artist who made it with appleseed for Max.

**Comment by juancarlosgzrz** [comment]
@xelatihy hit me up with a pm in twitter
