### ISSUE TITLE
Update website to reflect the latest release to be 2.0.5-beta?

### ISSUE THREAD

**Issue by luzpaz** [appleseedhq/appleseed#2652]
Based on https://github.com/appleseedhq/appleseed/releases/tag/2.0.5-beta

**Comment by luzpaz** [comment]
Sorry please move this issue to https://github.com/appleseedhq/appleseedhq.github.io

**Comment by est77** [comment]
2.0.5 is an internal release for use in the next Gafferseed update. The last official release is 2.0.0

**Comment by luzpaz** [comment]
Sorry, when's the next official release ? I'm asking as a packager

**Comment by est77** [comment]
Very likely during July

**Comment by dictoon** [comment]
> I'm asking as a packager

@luzpaz Out of curiosity, a packager for what distro or application?

**Comment by luzpaz** [comment]
@dictoon not for a specific distro per se, it's really for FreeCAD (https://github.com/FreeCAD/FreeCAD-render/blob/master/renderers/Appleseed.py). I'm trying to get other distros then the following below to incorporate appleseed in to their package ecosystem.

[![Packaging status](https://repology.org/badge/vertical-allrepos/appleseed.svg?header=appleseed)](https://repology.org/project/appleseed/versions)

**Comment by dictoon** [comment]
Awesome!

**Comment by luzpaz** [comment]
Also I'm tracking libregraphics/audio packages in https://github.com/luzpaz/libregraphics-package-tracking
