### ISSUE TITLE
Add DOI for scientific citation to the repository

### ISSUE THREAD

**Issue by yannci** [appleseedhq/appleseed#2684]
First of all I'd like to thank you for your amazing work here with appleseed!

We are currently working on a research project in our Master Degree Program and decided to use appleseed as our rendering engine for synthetic spectral images. Although there are renderers like mitsuba that's major purpose is a scientific use we wanted to evaluate appleseed as an alternative because of it's widely adoption in known DCC's and to give students with a different background then CGI (The research project is about color science mostly worked on by students with a more cineastic/film background) the ability to jump in right away where the integration in blender or gaffer comes in really handy.

Due to this I'd like to request to make appleseed more easy to use in a scientific environment and add a DOI to the repository as described on the GitHub blog here:
https://github.blog/2014-05-14-improving-github-for-science/

I'm not sure if this only works for educational and scientific repositories only but it seems not to be a big deal to add this badge.

I'd love to hear your options on this and thanks in advance
Yannic

**Comment by Mango-3** [comment]
Hi Yannic,
thanks for the suggestion and kind words. Citing appleseed is already possible (see example of a BibTeX entry for R below) but having a DOI is definitely an improvement worth considering.

You should join our [Discord server](https://discord.gg/dNCE5J8) to discuss this with @dictoon
 
On Discord you will get also real-time updates on appleseed development, our roadmap and access to regular test builds of our plugins for Max, Maya & Blender.


> To cite R in publications, use
> 
> @Manual{,
>   title        = {R: A Language and Environment for Statistical
>                   Computing},
>   author       = {{R Core Team}},
>   organization = {R Foundation for Statistical Computing},
>   address      = {Vienna, Austria},
>   year         = YEAR,
>   url          = {https://www.R-project.org}
> }

**Comment by dictoon** [comment]
Hi @yannci,

Thanks for reaching out!

One of the untold goal of appleseed is to be a great learning, teaching and experimentation platform.

I've used it a few times as a teaching support when giving master classes at [Ludwigsburg's Filmakademie](https://www.filmakademie.de/): it was very useful to explain the characteristics and limits of various rendering algorithms (path tracing without and with next event estimation, light tracing, etc.)

I'll look into creating a DOI for appleseed. It makes a lot of sense.

Please keep us informed on how things go with using appleseed in your master degree program. If you need anything or encounter any issue, please let us know here or on Discord, our team will be most happy to help.

Cheers!

**Comment by dictoon** [comment]
I'm in the process of publishing our latest official release (2.0.0-beta) and our upcoming release (2.1.0-beta) to Zenodo.

One point that is unclear to me at this time is which contributors to include as software author. I've posted a question to Stack Exchange Academia: 
https://academia.stackexchange.com/questions/135625/

@yannci You undoubtly has more experience than me on the subject, I would love to hear your opinion on the topic.

**Comment by dictoon** [comment]
Here is a tentative publication of the appleseed 2.0.0-beta release to Zenodo: https://zenodo.org/record/3384658

Feedback welcome!

**Comment by yannci** [comment]
@Mango-3 sorry for the late response I was busy the last few days. Thanks for giving the R example. I was already aware of the "@misc" entry in BibTex but with some kind of literature software as Citavi it's easy to use the DOI. And even the introduction with Zenodo gives you the possibility to export directly as BibTex. Nonetheless thanks a lot for this hint! Hopefully it will be useful for someone in the future.

@dictoon Thanks a lot for adding this so fast! Regarding my expertise in citing I'm not really more experienced then you I guess. I'm used to cite publications but no software until know. I think the suggestions on Stack Exchange are the best way to set this up as you already did.

Currently or project just started and my part was evaluating the tools with it's possibilities and make a decision about which to use but appleseed will be the backbone for creating synthetic images.
Thanks for looking into this and all the effort you put into appleseed!

**Comment by dictoon** [comment]
DOI for appleseed 2.0.0-beta: https://zenodo.org/record/3384658
DOI for appleseed 2.1.0-beta: https://zenodo.org/record/3456967
