### ISSUE TITLE
Set CMAKE_CXX_STANDARD_REQUIRED (to ON) and CMAKE_CXX_EXTENSIONS (to OFF) in top-level CMakeLists.txt

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2696]
See:

https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD_REQUIRED.html
https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_EXTENSIONS.html

**Comment by oktomus** [comment]
Ah there is a flag for this ! The whole time I was using CMAKE_CXX_FLAGS 💀
