### ISSUE TITLE
After loading project that uses texture-controlled sampler, wrong sampler is shown in settings

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2698]
It shows `Uniform` instead of `Texture`.

**Comment by saisriram2710** [comment]
Hi, where do I look at to try and fix this?

**Comment by dictoon** [comment]
Hi, the problem is probably in `src/appleseed.studio/mainwindow/renderingsettingswindow.cpp`.

**Comment by saisriram2710** [comment]
Hi, when I try to compile renderingsettingswindow.cpp, error displayed is:

utility/windowbase.h : no such file or directory

The compiler I have used is G++ 7.4.0.

How do I resolve?

**Comment by dictoon** [comment]
Everything else compiles? Can you post the full compilation log (as an attached text file)?

**Comment by saisriram2710** [comment]
[log.txt](https://github.com/appleseedhq/appleseed/files/3640853/log.txt)
Is this what you meant by the compilation log?
