### ISSUE TITLE
Replace foundation types (e.g. uint32) by std types (e.g. std::uint32_t)

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2705]

**Comment by saisriram2710** [comment]
Hi, I am new here and I have begun working on this. Why exactly should this be done?

**Comment by dictoon** [comment]
Hi, welcome! There's no point in having our own types now that the standard library provides perfectly good integral types (it wasn't the case in C++03).

**Comment by saisriram2710** [comment]
Makes sense, yes. Thanks. I'll work on replacing them.

**Comment by saisriram2710** [comment]
Hi, in-
appleseed/src/appleseed/renderer/utility, there is a line:
`out_depth_map["uint8"] = TypeDesc::UINT8;`

Should it be modified as:
`out_depth_map["std::uint8_t"] = TypeDesc::UINT8;`

**Comment by saisriram2710** [comment]
In a similar doubt, should the change be done for instances such as:
`foundation::uint32 m_object_instance_index;`
in appleseedhq/appleseed/src/appleseed/renderer/kernel/intersection/trianglekey.h?

**Comment by saisriram2710** [comment]
Should this be done to float variables as well?

**Comment by oktomus** [comment]
Hi @saisriram2710, you should come on our discord to talk with us more easily about code :) https://discord.gg/dNCE5J8

**Comment by oktomus** [comment]
> Should it be modified as: `out_depth_map["std::uint8_t"] = TypeDesc::UINT8;`

I don't think so. I don't know the context of this, let's talk about this in #dev on discord.

**Comment by oktomus** [comment]
> Should this be done to float variables as well?
You mean std::float ? If so, no.

**Comment by oktomus** [comment]
> Whenever there is an occurrence of foundation::uintx, do I change it to std::uintx? And I have noticed that when uintx occurs singly, there is a namespace foundation bracket encompassing the code. So when I change uintx into std::uintx_t, do I remove namespace foundation or do other parts of the code still depend on it?

Do you have an exemple ?

**Comment by dictoon** [comment]
Done.
