### ISSUE TITLE
Uniform scale test is not robust enough for analytic lights

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2728]
See scene `sandbox\tests\test scenes\analytic lights\04 - disk - analytic.appleseed`. It outputs the following warning:
> transform of disk object "disk_obj" has a non-uniform scale factor; scale will be ignored.

But the matrix looks uniform.

We may need to the following :
- Introduce some threshold in the scale transform components test

**Comment by dictoon** [comment]
Are you sure the scaling is actually uniform? Isn't there a -1 scaling along one dimension?

**Comment by oktomus** [comment]
There it is 

    <matrix>
    1.00000000000000000 0.00000000000000000 0.00000000000000000 0.00000000000000000
    0.00000000000000000 0.00000000000000000 1.00000000000000000 0.55000000000000004
    0.00000000000000000 1.00000000000000000 0.00000000000000000 0.00000000000000000
    0.00000000000000000 0.00000000000000000 0.00000000000000000 1.00000000000000000
    </matrix>

**Comment by dictoon** [comment]
What scale factors are reported?

**Comment by oktomus** [comment]
I haven't checked yet

**Comment by oktomus** [comment]
Disk wordl space scale :
    -1 1 1



    std::cout << "\nDisk world space scale : \n";
    std::cout << scale.x << " " << scale.y << " " << scale.z << "\n";
    std::cout << std::endl;

**Comment by oktomus** [comment]
Shouldn't we consider -1, 1 to be uniform for this case .

**Comment by dictoon** [comment]
I guess we could but I don't see a reason to justify the complexity. It feels reasonable to ask that the object has (1, 1, 1) scaling.
