### ISSUE TITLE
as_texture2surface is missing all metadata

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/appleseed#2744]
Originally posted in 

https://github.com/appleseedhq/blenderseed/issues/477

**Comment by est77** [comment]
This is not a bug. texture2surface is an utility shader used to preview texture swatches and things like that. It should be skipped by all plugins and not shown in UIs.
Plugins should create the shader and insert it directly into scenes when previewing textures.

**Comment by dictoon** [comment]
Thanks @est77! Created a new ticket on blenderseed's side: https://github.com/appleseedhq/blenderseed/issues/491
