### ISSUE TITLE
Black-body emission not working unless emission color is non-black in asStandardSurface

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2765]
In the `asStandardSurface` material, if emission color is pure black (zero), then black-body emission is disabled. Any non-black emission color makes black-body radiation work correctly.

![image](https://user-images.githubusercontent.com/321290/72683629-4f3e0400-3ad9-11ea-91ce-2932f8287db3.png)

**Comment by laurelkeys** [comment]
@dictoon I think this can be closed now 🙂

**Comment by dictoon** [comment]
Indeed, thanks!
