### ISSUE TITLE
Move `QDir::toNativeSeparators()` calls to `get_open_filename()` and similar functions

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2778]

**Comment by ani1998ket** [comment]
hey @dictoon could you please elaborate on what needs to be done for this particular issue?

**Comment by oktomus** [comment]
@ani1998ket Take a look at `toNativeSeparators` calls in the source code. These calls should be done in `get_open_filename` so that the path returned by `get_open_filename` always work on all platforms

**Comment by dictoon** [comment]
To be precise, it will always work on all platforms, regardless of whether `toNativeSeparators()` is called or not because the `/` path separator is also supported on Windows. The purpose of this call is just to make log messages nicer.

**Comment by Aaron19960821** [comment]
I would like to look into this issue. Please assign it to me. :D

**Comment by oktomus** [comment]
@Aaron19960821 No need to assign it, you can just say you are working on it here :)
