### ISSUE TITLE
Include total test suite execution time in HTML report

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2844]
The total test suite execution time is already measured and displayed in the console. This information, as well as the total number of passed/failed tests, should be included in the HTML report.

**Comment by oktomus** [comment]
See `scripts/runtestsuite/runtestsuite.py`.

Originally from https://github.com/appleseedhq/appleseed/issues/2847

**Comment by h44rd** [comment]
Hi, I'd like to take this issue up. I've gone through the `scripts/runtestsuite/runtestsuite.py`  file and there are two types of reports (simple and detailed). Is the total execution time required to be in both the types of the reports?

**Comment by oktomus** [comment]
@h44rd  That would be great to have it in both :)

- html : http://testsuite.appleseedhq.net:8080/current-job/sandbox/tests/test%20scenes/report.html
- and txt : http://testsuite.appleseedhq.net:8080/current-job/sandbox/tests/test%20scenes/testsuite_script_log.txt
