### ISSUE TITLE
Include commit hash (and possibly title) in test suite HTML report

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/appleseed#2853]
See `scripts/runtestsuite/runtestsuite.py`

Issue originally from https://github.com/appleseedhq/appleseed/issues/2847

**Comment by himanshujaidka** [comment]
Where do I get scripts folder?

**Comment by oktomus** [comment]
@himanshujaidka It's here https://github.com/appleseedhq/automated-test-suite

**Comment by himanshujaidka** [comment]
I mean I have downloaded all the files but unable to find this particular file that you mention above

**Comment by himanshujaidka** [comment]
I want to solve this issue and I am fresher so pls guide me on how I i'll solve this issue? Please help me out!

**Comment by oktomus** [comment]
Ah, it's here https://github.com/appleseedhq/appleseed/blob/master/scripts/runtestsuite/runtestsuite.py

**Comment by oktomus** [comment]
The HTML report is a file generated by the test runner. Have you ever ran appleseed or the test suite ?

**Comment by himanshujaidka** [comment]
I have installed appleseed

**Comment by himanshujaidka** [comment]
and runs an Appleseed application

**Comment by himanshujaidka** [comment]
but only once 😅 checked the sample piece which is pre-built by the community

**Comment by himanshujaidka** [comment]
If u will guide me then it's my pleasure 😅

**Comment by oktomus** [comment]
You should come on Discord, the link is in the README. For more information on how to use appleseed, check https://appleseedhq.net/, for developers info, check the wiki https://github.com/appleseedhq/appleseed/wiki.

You can ask for help on the forum https://forum.appleseedhq.net/

**Comment by himanshujaidka** [comment]
Your discord id?

**Comment by himanshujaidka** [comment]
Ok, I got it :)

**Comment by 85ayush** [comment]
hello I would love to work on this issue. Can you please guide me.

**Comment by oktomus** [comment]
It was already tackled by @russkev in #2903. Sorry
