### ISSUE TITLE
Build issue with Qt 5.2 (OS X, Xcode 5.0.2)

### ISSUE THREAD

**Issue by nyotis** [appleseedhq/appleseed#302]
you plan to update codebase to support Qt 5.2?

CMake Error at /Applications/CMake 2.8-12.app/Contents/share/cmake-2.8/Modules/FindQt4.cmake:1386 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  appleseed.studio/CMakeLists.txt:37 (find_package)

**Comment by dictoon** [comment]
Superseded by #2184.
