### ISSUE TITLE
Expose appleseed build options in appleseed.cli

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#304]
As AS is open source and can be compiled on many different platforms, it could be interesting to have an option to display building options:
- System version
- Compiler infos (version and flags of the command line)
- Compilation env vars (in the case of Linux this is very important)
- Library versions (to track potential dep problems)

This would really help if their is support to do: _appleseed.cli --version --build-options_. And avoid: "Please, run --versions for every dependency in your system". I don't know if it's hard to do but it would also make possible to compare your custom _hand shaped_ version with the _official build_.

**Comment by dictoon** [comment]
Library versions are now available via the `--libraries` command line option for appleseed.cli and in the About dialog of appleseed.studio.

**Comment by dictoon** [comment]
Done.
