### ISSUE TITLE
Implement nested dielectrics

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#319]
In many advertising shots, you need a lot of nice looking liquid and glass material. A common problem encounter is how make the refraction continue on two different (but in contact) objects.

There is the [JF Nested Dielectric](https://github.com/Psyop/jf-nested-dielectric) for Arnold created by Jonah Friedman following [this paper](http://graphics.idav.ucdavis.edu/~bcbudge/deep/research/nested_dielectrics.pdf) that seems under BSD licence (compatible with MIT?).

The [result](https://vimeo.com/86272108) is amazing.

Do you think it could be added to appleseed simply?

**Comment by est77** [comment]
Implemented in #948
