### ISSUE TITLE
Add a debug AOV to have render time per pixel

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#333]
When you have big render times, it can be very interesting to have a debug AOV showing where the renderer is spending it's time.

To give you an overview, this render:

![](http://i.imgur.com/tkRbDdH.png)

Provide a such "time per pixel" buffer:

![](http://i.imgur.com/uwKsDdE.png)

(Images from a personal project from [Tristan North](http://www.imdb.com/name/nm2348845/), thanks to him!)

More it's bright, more it takes time.

There is may way to display time per pixel:
- A 0-1 range frame with reel range values stored in metadatas (and log if the final image doesn't support metadatas. This bring to the most visual feedback but it's difficult, when you put this image to Nuke, to get a pixel value and exactly know which time it represent. While visually immediate, this is not my personal taste.
- A 0-n range, where N is the pixel time in second.I think this is the more efficient because you can change the exposure value in Nuke and keep the reel pixel value available when you click on it. It's also the simpler to implement as you don't have to deal with a "final range" that imply to have the image finished.
### References
- Mental ray's [time per pixel diagnostic](https://elementalray.wordpress.com/2012/01/29/unified-sampling-redux/).
- It's called [cputime](https://support.solidangle.com/display/AFMUG/AOVs) in Arnold.

**Comment by luisbarrancos** [comment]
Reviving this. What is the status of this? An appleseed equivalent of RenderMan's __CPUtime would be **very** handy to immediatly diagnose potentially problematic bottlenecks.
Together with #1815 it would provide priceless tools to the shader writer (and not only).

**Comment by Narann** [comment]
I agree that _CPU time_ is maybe better than _render time_
