### ISSUE TITLE
Add sample counts AOV

### ISSUE THREAD

**Issue by Narann** [appleseedhq/appleseed#339]
Each channel would provide the number of:
- Direct samples (Red?)
- Indirect samples (Green?)
- Shadow samples (Blue?)
- Reflection samples (Alpha?)
- Refraction samples (?)

Mantra seems to have a such feature but I can't find documentation about it.
Mental ray provide a global "sample count" channel in its diagnose mode.

**Comment by dictoon** [comment]
We now have a `pixel_sample_count` AOV that shows the total number of samples taken for each pixels. It's only useful with the adaptive tile renderer.
