### ISSUE TITLE
Improve Disney material expressions dialog

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#562]

**Comment by dictoon** [comment]
I think this can wait until after 1.1.0-stable.

**Comment by dictoon** [comment]
A few things to improve:

* Use a fixed-width font.
* Espace shouldn't close the dialog (pressing Escape is also used to close the tooltips).
* Lines should be numbered.

**Comment by dictoon** [comment]
Disney material will be gone imminently.
