### ISSUE TITLE
Add an orthographic camera model

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#605]

**Comment by flexwang** [comment]
What does the Label Gafferseed mean?

**Comment by est77** [comment]
Gafferseed is a project to integrate appleseed into Gaffer 
http://imageengine.github.io/gaffer
Gaffer is an open source scene assembly and look development application developed 
by Image Engine.

**Comment by flexwang** [comment]
Ok~Does implementing this feature involve coding in Gaffer?

**Comment by est77** [comment]
No. Tickets with the Gafferseed label are things that we need to implement, modify or fix in appleseed in order to have a better Gaffer integration.

For tickets related to work in Gaffer I think that Gaffer's repository would be the best place to add them.

The reason for this ticket is that Gaffer has an orthographic camera but appleseed does not,
so Gaffer scenes using this camera type cannot be translated correctly right now.
The work here would be creating a new Camera subclass in appleseed, similar to the ones already existing.

**Comment by flexwang** [comment]
Thanks for the explanation. Is this feature assigned already? I think I can give a try.

**Comment by dictoon** [comment]
It's not assigned yet. Do give it a try!

**Comment by dictoon** [comment]
Done in 7b89360d1bc68e3a7ebddd8a2561033042c85c6b.

Light tracing is not supported yet.

**Comment by dictoon** [comment]
Sorry @flexwang, but we needed orthographic cameras so I went ahead and implemented them. Don't hesitate to compare your implementation and the one I commited.

**Comment by flexwang** [comment]
oh that's ok. I think I can learn a lot by viewing the implementation.

**Comment by dictoon** [comment]
With 9c064dbbd76ee45ef7a4b68787355e5f5e9bde02, light tracing is now supported for all cameras.
