### ISSUE TITLE
Refactor Microfacet BRDF code

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#665]
There are 3 copies of the microfacet BRDF code with slight differences, one in microfacetbrdf, 
another one in the disneybrdf and the last one in  oslmicrofacetbrdf.
Now that all of them are using the new microfacet classes, the code can be refactored.

**Comment by dictoon** [comment]
Can this issue be closed?

**Comment by est77** [comment]
Done in cd9699c4cfd1c2c45b927a558c238678c2d45d8f.
