### ISSUE TITLE
Speed up float-to-half conversions

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#713]
These take a noticeable amount of time when doing interactive rendering with a frame using the 'half' pixel type (which is the default).

This code is probably a great starting point for this task:
https://gist.github.com/rygorous/2156668
https://gist.github.com/rygorous/2144712

**Comment by est77** [comment]
For reference: https://github.com/OpenImageIO/oiio/pull/494

**Comment by dictoon** [comment]
> For reference: OpenImageIO/oiio#494

From the link:

> Closing this as obsolete. SSE is a much better way to go.
