### ISSUE TITLE
Add a short help string to Entities input metadata

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#745]
Could be used by automatic documentation tools and for tooltips in integration plugins for example.

**Comment by Narann** [comment]
I'm not an expert but is it really smart to embeed string doc inside libs instead of leaving this into a separate, UI only, file? This way you could have .so file + <entity_name>_doc.xml (for example) file.

**Comment by est77** [comment]
We already have entity metadata in the C++ library: https://github.com/appleseedhq/appleseed/blob/master/src/appleseed/renderer/modeling/light/directionallight.cpp#L260

The metadata is also accesible from Python:
https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.python/bindlight.cpp#L78

I think it's very convenient and you can choose the best language to access it depending on your project (usually that would be python). It would be very easy to write a simple python script to convert the metadata to XML or JSON.

I started the work to document the GafferSeed nodes and I need the help strings. I'd like them to be in a central place where other tools / plugins like blenderseed can also access them.

**Comment by johnhaddon** [comment]
Having the help strings be queryable directly from the Appleseed API sounds like a great thing to me. If there's a genuine concern about lots of strings in the library itself, then the API could load the metadata from an external file behind the scenes. That way you can have external storage, but still make sure that N external clients don't all have to implement their own parsing for the metadata format. As long as there's an API, you can change the implementation behind the scenes at a later date as well.

**Comment by dictoon** [comment]
Totally agree with this, I've had this plan for a while now.

@Narann I think it makes sense to have built-in strings for built-in entities.

**Comment by dictoon** [comment]
> It would be very easy to write a simple python script to convert the metadata to XML or JSON.

Note that appleseed already ships with a tool called `dumpmetadata` that can dump all built-in entities metadata in either XML or Markdown format. Adding JSON or restricting dumping metadata of only a subset of entities would be trivial.
