### ISSUE TITLE
Review Bézier curve intersection code

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#768]
Compare our implementation with the one in PBRT:
https://github.com/mmp/pbrt-v3/blob/master/src/shapes/curve.cpp

Reproduce the issue reported (and fixed) by Koji, and create a test scene that demonstrates the fix:
https://github.com/appleseedhq/appleseed/pull/767#issuecomment-112521098

**Comment by lorentzo** [comment]
H!
I would like to look more into this issue and hopefully find a solution.

**Comment by dictoon** [comment]
Done.
