### ISSUE TITLE
Allow negative numbers for number of threads param in configurations

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#774]
-n number of threads would mean use (total number of cores - n) threads for rendering or in other words, leave n cores unused.

This would be useful in plugins when doing progressive rendering, where the unused cores would be used by the host application to keep the user interface responsive.

**Comment by Narann** [comment]
Interesting idea.

So:
* 0 = all threads
* n = n threads
* -n = all threads - n

**Comment by dictoon** [comment]
Almost:

* `auto` = one thread per logical core
* n = n threads
* -n = number of logical cores - n threads

**Comment by dictoon** [comment]
Done.
