### ISSUE TITLE
Disable Qt plugins in release packages

### ISSUE THREAD

**Issue by alexdmz** [appleseedhq/appleseed#835]
using Antergos Arch Linux Based distro,appleseed beta 1.2.0 every time i open appleseed.studio and try to open a new project appleseed crash, also if i want to open the about window, it does crash

**Comment by dictoon** [comment]
Does the command line version of appleseed work? Try

    ./appleseed.cli builtin:cornell_box -o render.png

to render the Cornell Box and provude a `render.png` file.

Could you run appleseed.studio under gdb to figure out the error? Try

    gdb appleseed.studio

Then type `run`. When appleseed.studio crashes, type `bt` in gdb to print the backtrace. Could you then send us this output?

**Comment by alexdmz** [comment]
yes the command line version works fine, for the gbd command not sure how to run it, 
 i tried ./appleseed.studio gbd and appleseed it does run but it crash just in the moment it runs , also i found that if a tried to open "Tests" , "Benchmarks" ,"Render Settings" appleseed also crash

**Comment by dictoon** [comment]
If you have gdb (GNU Debugger) installed, typing exactly this:

    gdb appleseed.studio

in a terminal inside the `bin/` directory of your appleseed installation will start gdb and load appleseed.studio in it. Typing `run` inside gdb will then start appleseed.studio.

If you don't have gdb installed, maybe installing it is an option?
Could you try older versions of appleseed maybe?
Are you able to run other Qt programs?

In any case it sounds like some kind of Qt problem. Could you be more specific about what works, and what crashes?

**Comment by alexdmz** [comment]
yes i think indeed its a Qt problem, kind of strange cause i use and run other Qt programs

i got this as a result of gdb
 
>Starting program: /home/alejandro/appleseed/bin/appleseed.studio 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40806)
Program received signal SIGABRT, Aborted.
0x00007ffff010c528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff010c528 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff010d93a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff397bd64 in qt_message_output(QtMsgType, char const*) ()
   from /home/alejandro/appleseed/bin/../lib/libQtCore.so.4
#3  0x00007ffff397bf09 in qt_message(QtMsgType, char const*, __va_list_tag*) () from /home/alejandro/appleseed/bin/../lib/libQtCore.so.4
#4  0x00007ffff397c811 in qFatal(char const*, ...) ()
   from /home/alejandro/appleseed/bin/../lib/libQtCore.so.4
#5  0x00007ffff3aa870c in QObjectPrivate::QObjectPrivate(int) ()
   from /home/alejandro/appleseed/bin/../lib/libQtCore.so.4
#6  0x00007fffdf57f11d in QSvgRenderer::QSvgRenderer(QString const&, QObject*) () from /usr/lib/libQtSvg.so.4
#7  0x00007fffdb4cd792 in ?? ()
   from /usr/lib/qt4/plugins/iconengines/libqsvgicon.so
#8  0x00007fffdb4cb420 in ?? ()
   from /usr/lib/qt4/plugins/iconengines/libqsvgicon.so
#9  0x00007ffff4067410 in QIcon::addFile(QString const&, QSize const&, QIcon::Mode, QIcon::State) ()
   from /home/alejandro/appleseed/bin/../lib/libQtGui.so.4

**Comment by est77** [comment]
Can you do a quick test?
In a terminal, try this:

export LD_LIBRARY_PATH=/home/alejandro/appleseed/lib
/home/alejandro/appleseed/bin/appleseed.studio

**Comment by alexdmz** [comment]
yes....okay i ran those command's, it makes applessed run as normal, still getting the crashing problem's

>export LD_LIBRARY_PATH=/home/alejandro/appleseed/lib
export LD_LIBRARY_PATH=/home/alejandro/appleseed/bin/appleseed.studio
/home/alejandro/appleseed/bin/appleseed.studio

**Comment by dictoon** [comment]
That makes no sense; type *exactly* this:

    export LD_LIBRARY_PATH=/home/alejandro/appleseed/lib
    /home/alejandro/appleseed/bin/appleseed.studio

**Comment by alexdmz** [comment]
i also did that , program run's ,still getting the crashing problem's

**Comment by est77** [comment]
I think the reason appleseed.studio is crashing is because of Qt's SVG plugin.
We don't bundle it because we don't use SVG, but Qt is finding the plugin in your system's Qt install and crashes when trying to load it because of incompatible versions (4.8.7 vs 4.8.6).

We have to improve our linux package to handle these kind of situations.

**Comment by est77** [comment]
Can you do another quick test?

cd /home/alejandro/appleseed/bin
touch qt.conf
/home/alejandro/appleseed/bin/appleseed.studio

**Comment by alexdmz** [comment]
Problem solved,after entering and runing those commands, appleseed work's just fine now, able to open the mentioned menus normally without any crash

**Comment by est77** [comment]
We'll include an empty qt.conf file (or an equivalent nicer solution) in the next release.
Thanks for helping us fixing this issue.

**Comment by alexdmz** [comment]
glad to help, if you need any tester or somethink like that for the linux version of appleseed, im willing to help in the future

**Comment by est77** [comment]
Fix here: 758bb96f34190cb6d1d8cd

**Comment by dictoon** [comment]
Fixed.
