### ISSUE TITLE
Add support for C++ plugins to appleseed.studio

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#876]

**Comment by nyue** [comment]
Is this related in some ways to procedural geometry DSO or pave the way towards that possibility ?

**Comment by dictoon** [comment]
It is strongly related.

Supporting procedural geometry is high on our list. We basically need to introduce the concept of procedural assemblies, i.e. assemblies whose geometry content is defined by functions (which can then be implemented as DSOs).

**Comment by Narann** [comment]
I guess after this we could write a appleseed procedural having a renderman procedural as argument and convert Ri calls to appleseed stuff...

**Comment by dictoon** [comment]
The intent for this ticket isn't clear anymore. appleseed core now supports C++ plugins, and appleseed.studio now supports Python plugins. We don't have plans to support C++ plugins in appleseed.studio.
