### ISSUE TITLE
Get rid of std::auto_ptr<> (deprecated in C++11)

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#93]
The idea is to replace `std::auto_ptr<>` by [`std::unique_ptr<>`](http://en.cppreference.com/w/cpp/memory/unique_ptr) everywhere.

Since `std::unique_ptr<>` supports custom _deleters_, it could also replace `foundation::auto_release_ptr<>` (with an appropriate deleter that would call `release()` to delete the instance).

This task implies that we accept C++11 constructs in the code base. This will require to first check that all the compilers we are using support a reasonable subset of C++11.

**Comment by Narann** [comment]
Following [VFX Reference Platform](http://www.vfxplatform.com/), C++11 products are supposed to be shipped in 2016. Who can't switch to C++11 exactly?

**Comment by dictoon** [comment]
I think Maya is the biggest roadblock right now, as far as I know on Linux it's still compiled with an old version of gcc (4.2? not sure).

**Comment by Narann** [comment]
From [Maya 2016 doc](http://help.autodesk.com/view/MAYAUL/2016/ENU/?guid=__files_Setting_up_your_build_environment_Linux_compiler_requirement_htm):

> Maya is built on RHEL 6.5 which has a system default gcc 4.4.7 compiler.
>
> Use the system default g++ compiler; or, if additional C++11 features are required, use Red Hat’s Developer Toolset 2.1.

**Comment by est77** [comment]
Done in #1655
