### ISSUE TITLE
appleseed.studio's Save Project As... does not save search paths

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#960]
If a project containing search paths is opened in studio and saved as with a new name, 
search paths are not saved.

**Comment by dictoon** [comment]
It seems like this was intentional:
https://github.com/appleseedhq/appleseed/commit/a745600d90e2e95d5e7f73a7995072b0ba19d2b3

**Comment by dictoon** [comment]
Fixed in 9b61581ab9404627fdada8eb241715d1e8066961.
