### ISSUE TITLE
 error MSB6006: "cmd.exe" exited with code -1073741515.

### ISSUE THREAD

**Issue by wubugui** [appleseedhq/appleseed#974]
I build appleseed.studio with VS2013 community but at last get one error:

>
1>------ Build started: Project: appleseed.studio, Configuration: Debug x64 ------
1>  Generating ui_benchmarkwindow.h
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code -1073741515.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

I have set QT to my PATH,but it still does not work.

**Comment by est77** [comment]
Can you try to increase the verbosity as explained here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a813616d-5fa4-481d-934f-cea6126d2f62/error-msb6006-cmdexe-exited-with-code-3?forum=vcgeneral

I don't have access to windows so I cannot be sure, but this looks maybe like a Qt install 
problem? For example, the command to generate the dialogs code from the ui files could be failing.

**Comment by wubugui** [comment]
i have found that i didn't install the vc runtime.
now i solved it,still thank you vert much.
