### ISSUE TITLE
Add keyboard shortcuts to tooltips in appleseed.studio

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#988]

**Comment by ucanbizon** [comment]
![applesoru](https://cloud.githubusercontent.com/assets/7409367/24589799/fc47d440-17f1-11e7-8cec-4e2776df87f0.png)
Is it like adding "F5" to end of the text, which looks like "Start Interactive Rendering F5".

**Comment by dictoon** [comment]
Yes. In parentheses: *Start Interactive Rendering (F5)*
